// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thread_.NET.DAL.Context;

namespace Thread_.NET.DAL.Migrations
{
    [DbContext(typeof(ThreadContext))]
    [Migration("20210604101115_AddDislikes")]
    partial class AddDislikes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 3,
                            Body = "Repudiandae quisquam sunt tempore vel in.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 181, DateTimeKind.Local).AddTicks(3777),
                            PostId = 19,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 181, DateTimeKind.Local).AddTicks(5654)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 5,
                            Body = "Esse repellendus sunt et cupiditate ipsum consequatur eos earum possimus.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 181, DateTimeKind.Local).AddTicks(7128),
                            PostId = 9,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 181, DateTimeKind.Local).AddTicks(7162)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 10,
                            Body = "Repellendus qui dolor debitis voluptate explicabo quia ipsa.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 181, DateTimeKind.Local).AddTicks(7516),
                            PostId = 8,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 181, DateTimeKind.Local).AddTicks(7549)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            Body = "Commodi ea vitae eum sed ut voluptatum necessitatibus.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 181, DateTimeKind.Local).AddTicks(7870),
                            PostId = 17,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 181, DateTimeKind.Local).AddTicks(7898)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 16,
                            Body = "Non voluptatibus in ducimus rem accusamus.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 181, DateTimeKind.Local).AddTicks(8323),
                            PostId = 20,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 181, DateTimeKind.Local).AddTicks(8352)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 1,
                            Body = "Labore veritatis voluptatem recusandae placeat dolores et dolorem.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 181, DateTimeKind.Local).AddTicks(8664),
                            PostId = 15,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 181, DateTimeKind.Local).AddTicks(8688)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 8,
                            Body = "Delectus et qui perspiciatis quia sunt dolorum animi tempore minima.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 181, DateTimeKind.Local).AddTicks(9004),
                            PostId = 6,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 181, DateTimeKind.Local).AddTicks(9028)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 14,
                            Body = "Reprehenderit exercitationem velit corporis a dolorum laboriosam nostrum atque.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 181, DateTimeKind.Local).AddTicks(9336),
                            PostId = 11,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 181, DateTimeKind.Local).AddTicks(9363)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 7,
                            Body = "Qui ratione harum ipsa assumenda.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 181, DateTimeKind.Local).AddTicks(9587),
                            PostId = 17,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 181, DateTimeKind.Local).AddTicks(9609)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 9,
                            Body = "Debitis molestiae explicabo nesciunt doloremque voluptas.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 182, DateTimeKind.Local).AddTicks(107),
                            PostId = 5,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 182, DateTimeKind.Local).AddTicks(140)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 10,
                            Body = "Exercitationem qui saepe est.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 182, DateTimeKind.Local).AddTicks(390),
                            PostId = 11,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 182, DateTimeKind.Local).AddTicks(413)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 11,
                            Body = "Exercitationem adipisci quia quam quis et.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 182, DateTimeKind.Local).AddTicks(638),
                            PostId = 17,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 182, DateTimeKind.Local).AddTicks(659)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 20,
                            Body = "Dolore voluptatibus earum doloribus iste.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 182, DateTimeKind.Local).AddTicks(860),
                            PostId = 20,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 182, DateTimeKind.Local).AddTicks(881)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 14,
                            Body = "Et tenetur delectus velit ipsa enim.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 182, DateTimeKind.Local).AddTicks(1103),
                            PostId = 5,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 182, DateTimeKind.Local).AddTicks(1126)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 13,
                            Body = "Dolores consectetur quia.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 182, DateTimeKind.Local).AddTicks(1311),
                            PostId = 11,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 182, DateTimeKind.Local).AddTicks(1332)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 20,
                            Body = "Id dolor maxime sunt aspernatur et illo modi.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 182, DateTimeKind.Local).AddTicks(1564),
                            PostId = 6,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 182, DateTimeKind.Local).AddTicks(1582)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 10,
                            Body = "Repellendus ut odio aliquam mollitia iure deleniti qui voluptates.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 182, DateTimeKind.Local).AddTicks(1963),
                            PostId = 12,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 182, DateTimeKind.Local).AddTicks(1993)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 11,
                            Body = "Aliquam molestiae culpa dolor veniam.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 182, DateTimeKind.Local).AddTicks(2225),
                            PostId = 6,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 182, DateTimeKind.Local).AddTicks(2246)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 2,
                            Body = "Optio quisquam enim laboriosam vel vel suscipit accusamus.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 182, DateTimeKind.Local).AddTicks(2483),
                            PostId = 17,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 182, DateTimeKind.Local).AddTicks(2505)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 17,
                            Body = "Sit voluptates velit atque veniam et fugiat ut.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 182, DateTimeKind.Local).AddTicks(2753),
                            PostId = 14,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 182, DateTimeKind.Local).AddTicks(2774)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDislike")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("CommentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentId = 5,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 215, DateTimeKind.Local).AddTicks(7327),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 215, DateTimeKind.Local).AddTicks(8850),
                            UserId = 5
                        },
                        new
                        {
                            Id = 2,
                            CommentId = 15,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 215, DateTimeKind.Local).AddTicks(9869),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 215, DateTimeKind.Local).AddTicks(9884),
                            UserId = 7
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 14,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 215, DateTimeKind.Local).AddTicks(9952),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 215, DateTimeKind.Local).AddTicks(9961),
                            UserId = 16
                        },
                        new
                        {
                            Id = 4,
                            CommentId = 16,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(20),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(29),
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CommentId = 8,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(82),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(91),
                            UserId = 10
                        },
                        new
                        {
                            Id = 6,
                            CommentId = 2,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(144),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(152),
                            UserId = 11
                        },
                        new
                        {
                            Id = 7,
                            CommentId = 2,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(203),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(212),
                            UserId = 5
                        },
                        new
                        {
                            Id = 8,
                            CommentId = 2,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(262),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(271),
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            CommentId = 5,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(554),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(569),
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            CommentId = 12,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(633),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(642),
                            UserId = 18
                        },
                        new
                        {
                            Id = 11,
                            CommentId = 17,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(695),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(704),
                            UserId = 12
                        },
                        new
                        {
                            Id = 12,
                            CommentId = 10,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(755),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(764),
                            UserId = 19
                        },
                        new
                        {
                            Id = 13,
                            CommentId = 15,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(813),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(822),
                            UserId = 20
                        },
                        new
                        {
                            Id = 14,
                            CommentId = 11,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(870),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(879),
                            UserId = 5
                        },
                        new
                        {
                            Id = 15,
                            CommentId = 4,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(928),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(936),
                            UserId = 10
                        },
                        new
                        {
                            Id = 16,
                            CommentId = 6,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(985),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(994),
                            UserId = 18
                        },
                        new
                        {
                            Id = 17,
                            CommentId = 8,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(1041),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(1050),
                            UserId = 18
                        },
                        new
                        {
                            Id = 18,
                            CommentId = 6,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(1099),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(1107),
                            UserId = 17
                        },
                        new
                        {
                            Id = 19,
                            CommentId = 4,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(1156),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(1165),
                            UserId = 9
                        },
                        new
                        {
                            Id = 20,
                            CommentId = 6,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(1214),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 216, DateTimeKind.Local).AddTicks(1223),
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 714, DateTimeKind.Local).AddTicks(6305),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/43.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 715, DateTimeKind.Local).AddTicks(7739)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 715, DateTimeKind.Local).AddTicks(9982),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/271.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(20)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(116),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1128.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(132)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(187),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/907.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(200)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(256),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/384.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(271)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(577),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/381.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(605)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(695),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/773.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(709)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(769),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/178.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(784)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(842),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1152.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(858)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(926),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/416.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(939)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(1002),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/659.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(1017)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(1071),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/514.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(1082)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(1135),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/872.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(1147)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(1201),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/415.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(1213)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(1271),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/727.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(1285)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(1338),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/820.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(1350)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(1607),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/607.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(1643)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(1731),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/735.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(1746)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(1810),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1208.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(1824)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(1888),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/393.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 716, DateTimeKind.Local).AddTicks(1902)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 727, DateTimeKind.Local).AddTicks(9897),
                            URL = "https://picsum.photos/640/480/?image=606",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(1659)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(2164),
                            URL = "https://picsum.photos/640/480/?image=516",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(2183)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(2256),
                            URL = "https://picsum.photos/640/480/?image=116",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(2274)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(2341),
                            URL = "https://picsum.photos/640/480/?image=523",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(2357)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(2592),
                            URL = "https://picsum.photos/640/480/?image=914",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(2613)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(2687),
                            URL = "https://picsum.photos/640/480/?image=96",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(2701)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(2766),
                            URL = "https://picsum.photos/640/480/?image=424",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(2783)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(2847),
                            URL = "https://picsum.photos/640/480/?image=1046",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(2862)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(2924),
                            URL = "https://picsum.photos/640/480/?image=674",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(2940)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(3003),
                            URL = "https://picsum.photos/640/480/?image=819",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(3020)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(3080),
                            URL = "https://picsum.photos/640/480/?image=823",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(3096)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(3162),
                            URL = "https://picsum.photos/640/480/?image=615",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(3178)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(3240),
                            URL = "https://picsum.photos/640/480/?image=363",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(3255)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(3317),
                            URL = "https://picsum.photos/640/480/?image=552",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(3331)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(3394),
                            URL = "https://picsum.photos/640/480/?image=531",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(3409)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(3471),
                            URL = "https://picsum.photos/640/480/?image=456",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(3485)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(3548),
                            URL = "https://picsum.photos/640/480/?image=536",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(3564)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(3859),
                            URL = "https://picsum.photos/640/480/?image=478",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(3883)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(3968),
                            URL = "https://picsum.photos/640/480/?image=908",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(3984)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(4046),
                            URL = "https://picsum.photos/640/480/?image=490",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 728, DateTimeKind.Local).AddTicks(4061)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PreviewId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PreviewId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 7,
                            Body = "veritatis",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 151, DateTimeKind.Local).AddTicks(8301),
                            PreviewId = 24,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 151, DateTimeKind.Local).AddTicks(9983)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 15,
                            Body = "rerum",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 152, DateTimeKind.Local).AddTicks(1388),
                            PreviewId = 30,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 152, DateTimeKind.Local).AddTicks(1416)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 18,
                            Body = "Aut est ratione perspiciatis et.\nDoloremque et totam dolores minus.\nId vel voluptatem et mollitia aut sed voluptatibus.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 161, DateTimeKind.Local).AddTicks(238),
                            PreviewId = 32,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 161, DateTimeKind.Local).AddTicks(414)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 9,
                            Body = "quas",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 161, DateTimeKind.Local).AddTicks(814),
                            PreviewId = 26,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 161, DateTimeKind.Local).AddTicks(852)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 9,
                            Body = "Optio atque corrupti magni vel.\nDistinctio id enim nesciunt aut ducimus neque doloribus velit.\nLaboriosam in rerum explicabo quaerat accusamus.\nQuos minima impedit ipsum voluptatum rerum ad consectetur.\nDolorem ex assumenda aut dolore deserunt modi id corrupti.\nQuis pariatur odit.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 161, DateTimeKind.Local).AddTicks(4805),
                            PreviewId = 31,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 161, DateTimeKind.Local).AddTicks(4856)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 7,
                            Body = "Non nulla sunt. Consequatur eum illum asperiores pariatur tempore id sit sapiente. Delectus magnam minima. Eius consectetur tempora maxime ex laboriosam id incidunt qui. Iure quod enim voluptatem perspiciatis laborum nisi nisi amet. Ut earum consectetur aliquam quod omnis.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 161, DateTimeKind.Local).AddTicks(9883),
                            PreviewId = 40,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 161, DateTimeKind.Local).AddTicks(9922)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 18,
                            Body = "magnam",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 162, DateTimeKind.Local).AddTicks(44),
                            PreviewId = 38,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 162, DateTimeKind.Local).AddTicks(56)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 6,
                            Body = "Et quod et amet quos ut neque.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 162, DateTimeKind.Local).AddTicks(1620),
                            PreviewId = 36,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 162, DateTimeKind.Local).AddTicks(1656)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 8,
                            Body = "est",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 162, DateTimeKind.Local).AddTicks(1894),
                            PreviewId = 23,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 162, DateTimeKind.Local).AddTicks(1910)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 1,
                            Body = "Aliquid eligendi dolorum et aut praesentium minima repellat.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 162, DateTimeKind.Local).AddTicks(2237),
                            PreviewId = 40,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 162, DateTimeKind.Local).AddTicks(2301)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 4,
                            Body = "Ipsum sit non provident atque. Eligendi et consequatur nesciunt at tenetur ut sunt. Consectetur facilis harum consectetur quo tempore impedit natus. Temporibus autem magni aliquid maxime.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 162, DateTimeKind.Local).AddTicks(2777),
                            PreviewId = 37,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 162, DateTimeKind.Local).AddTicks(2793)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 18,
                            Body = "Id voluptates quasi architecto fuga rerum mollitia fugiat ut.\nAssumenda fugit facilis rerum culpa aut voluptas.\nLaborum et et praesentium est.\nMaxime aut officia laboriosam inventore voluptatibus aut neque.\nQuis ut temporibus.\nSimilique aut unde.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 162, DateTimeKind.Local).AddTicks(3372),
                            PreviewId = 23,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 162, DateTimeKind.Local).AddTicks(3390)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 15,
                            Body = "accusantium",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 162, DateTimeKind.Local).AddTicks(3477),
                            PreviewId = 30,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 162, DateTimeKind.Local).AddTicks(3488)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 2,
                            Body = "Earum et illum beatae quaerat labore qui eos ea.\nExcepturi illo aliquam omnis natus.\nEst illo ad repudiandae autem soluta possimus.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 162, DateTimeKind.Local).AddTicks(3955),
                            PreviewId = 28,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 162, DateTimeKind.Local).AddTicks(3974)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 6,
                            Body = "Maxime dolorem quasi eum laboriosam.\nSed atque sequi vitae et magni eum.\nPorro labore et dolores eos inventore est laudantium.\nDolorum qui sit reiciendis quaerat quod praesentium perferendis maxime ducimus.\nReprehenderit ut quaerat magni quo est distinctio beatae ea.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 162, DateTimeKind.Local).AddTicks(4826),
                            PreviewId = 31,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 162, DateTimeKind.Local).AddTicks(4866)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 21,
                            Body = "dicta",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 162, DateTimeKind.Local).AddTicks(4974),
                            PreviewId = 23,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 162, DateTimeKind.Local).AddTicks(4986)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 3,
                            Body = "Et minus nobis minima minima qui non.\nOfficia vero quod.\nQuasi illo nobis reiciendis quaerat deleniti voluptatibus quis.\nQuia in provident veritatis consequatur consequatur nemo et quo.\nModi id ducimus explicabo porro.\nAut a aut velit.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 162, DateTimeKind.Local).AddTicks(5518),
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 162, DateTimeKind.Local).AddTicks(5535)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 4,
                            Body = "Blanditiis velit praesentium aut aut atque ut corrupti. Deleniti suscipit sequi eius voluptates dicta dolorum voluptas facere. Occaecati sunt dolorum sapiente delectus illum voluptatem. Quia ipsum beatae beatae mollitia adipisci aliquid.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 162, DateTimeKind.Local).AddTicks(5983),
                            PreviewId = 39,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 162, DateTimeKind.Local).AddTicks(6001)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 16,
                            Body = "Consequatur soluta sed nam laborum eum aut necessitatibus ab quisquam. Earum ut ut vel et fugiat labore. Nostrum minus sapiente consequatur ipsam impedit.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 162, DateTimeKind.Local).AddTicks(6407),
                            PreviewId = 29,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 162, DateTimeKind.Local).AddTicks(6441)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 10,
                            Body = "Sint est et autem possimus voluptas aut a ut qui. Quaerat voluptatum qui deserunt dolores qui ea eum id. Recusandae ex voluptas. Pariatur ipsam aut tenetur. Facilis ab voluptatem ab. Consequatur enim omnis deleniti aut rerum officiis necessitatibus et.",
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 162, DateTimeKind.Local).AddTicks(8202),
                            PreviewId = 30,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 162, DateTimeKind.Local).AddTicks(8249)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDislike")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("PostId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PostReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 199, DateTimeKind.Local).AddTicks(9428),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 5,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(1178),
                            UserId = 13
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(2548),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 10,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(2565),
                            UserId = 20
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(2641),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 6,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(2650),
                            UserId = 11
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(2706),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 14,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(2715),
                            UserId = 15
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(2771),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 2,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(2779),
                            UserId = 4
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(2832),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 9,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(2841),
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(2892),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 13,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(2901),
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(2951),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 15,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(2959),
                            UserId = 3
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(3009),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 2,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(3018),
                            UserId = 8
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(3069),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 8,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(3077),
                            UserId = 7
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(3126),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 10,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(3135),
                            UserId = 21
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(3185),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 3,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(3196),
                            UserId = 10
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(3246),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 18,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(3255),
                            UserId = 7
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(3304),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 7,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(3312),
                            UserId = 15
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(3429),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 1,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(3440),
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(3494),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 1,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(3503),
                            UserId = 6
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(3553),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 14,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(3561),
                            UserId = 5
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(3612),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 15,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(3622),
                            UserId = 16
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(3672),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 11,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(3681),
                            UserId = 19
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(3730),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 12,
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 200, DateTimeKind.Local).AddTicks(3738),
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AvatarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 4,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 819, DateTimeKind.Local).AddTicks(5778),
                            Email = "Giles44@hotmail.com",
                            Password = "bGTU9cfFGKFL0Mr2Ls+FRh0LRDseI1FrILR9st8KBN0=",
                            Salt = "0dzkZa1JZCSRhPgpHwOqSRXR1JTcCyP+eRgNV3EZ8tI=",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 819, DateTimeKind.Local).AddTicks(7736),
                            UserName = "Darian34"
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 7,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 833, DateTimeKind.Local).AddTicks(6038),
                            Email = "Caterina.Runolfsdottir91@gmail.com",
                            Password = "W8NJodxQHTnmQ9SEsA6Hh6G9u1S3t0Jx8yEbDmMPAYM=",
                            Salt = "iX05cBqoMl5Y+yHQyqXi26lwGITJyECgdru07Bboong=",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 833, DateTimeKind.Local).AddTicks(6176),
                            UserName = "Carrie_Bayer8"
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 847, DateTimeKind.Local).AddTicks(9743),
                            Email = "Kaley40@yahoo.com",
                            Password = "10LChylrSrQ79XACRC65k563tJW1BeLs2dwKU7Ouylk=",
                            Salt = "zyw5Qbw9t7NMpJ+aAcCNPcUalN3jgjqQysc+xiteXx4=",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 847, DateTimeKind.Local).AddTicks(9879),
                            UserName = "Wilson29"
                        },
                        new
                        {
                            Id = 4,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 864, DateTimeKind.Local).AddTicks(1749),
                            Email = "Tomasa.Schumm54@yahoo.com",
                            Password = "wdmT6fe+kxzdd+SIT+AKcbmXY8mm9fWh5cgibvN0g3E=",
                            Salt = "mGdeaJdFTj3zFRTXe2fWx3a36oi03Rh8xHpERU6/5n4=",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 864, DateTimeKind.Local).AddTicks(1880),
                            UserName = "Torey86"
                        },
                        new
                        {
                            Id = 5,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 882, DateTimeKind.Local).AddTicks(4408),
                            Email = "Sigurd.Kunze@gmail.com",
                            Password = "IoZbuf6ClVb0PxEiXHIYTiV31sO/fNwi3+DKJ4ONsso=",
                            Salt = "/8EYyaUEKGpUXeLqo29W8Xrb1ESQLNkxJXtM6a6C1vU=",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 882, DateTimeKind.Local).AddTicks(4566),
                            UserName = "Frederik.Herman36"
                        },
                        new
                        {
                            Id = 6,
                            AvatarId = 15,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 898, DateTimeKind.Local).AddTicks(6462),
                            Email = "Rodrick_West@yahoo.com",
                            Password = "u4FRzYTitnB7+zFtSUG50gXVA2mT9d7sFkGooO5MCEo=",
                            Salt = "0jfS1vuk3A0vM0mTd5dn13046JN3SH6WlEhkuD8XpGQ=",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 898, DateTimeKind.Local).AddTicks(6610),
                            UserName = "Trycia61"
                        },
                        new
                        {
                            Id = 7,
                            AvatarId = 10,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 910, DateTimeKind.Local).AddTicks(4652),
                            Email = "Arielle64@gmail.com",
                            Password = "LXJP/X5BWaYjXFjvmaHKXqxMnCqD0RTa4MvqKdx05kw=",
                            Salt = "qzJKLsC6fiMcqFe4e31CdbYUBxlA1joTDu43wa0aldQ=",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 910, DateTimeKind.Local).AddTicks(4787),
                            UserName = "Halle.Balistreri4"
                        },
                        new
                        {
                            Id = 8,
                            AvatarId = 5,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 924, DateTimeKind.Local).AddTicks(9565),
                            Email = "Tre79@yahoo.com",
                            Password = "1gJ8qKILjfvmvqwie1jgSmUIK3iwbO12Qzc8GUWieFM=",
                            Salt = "4zhP59OaEF+SZW+KDf3vxSnc4hDobWJ26kMRZd92CGs=",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 924, DateTimeKind.Local).AddTicks(9694),
                            UserName = "Beatrice.Padberg18"
                        },
                        new
                        {
                            Id = 9,
                            AvatarId = 15,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 942, DateTimeKind.Local).AddTicks(3875),
                            Email = "Theron26@yahoo.com",
                            Password = "l3eZrhLdOc3Rd5J8XyOJJpWN5ucAUsPNj1WOjQsuMhg=",
                            Salt = "rHts3ZsXt2nIvXQgC71fYqKVlPZLZEnVr1O5RDoliJY=",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 942, DateTimeKind.Local).AddTicks(4027),
                            UserName = "Delia18"
                        },
                        new
                        {
                            Id = 10,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 956, DateTimeKind.Local).AddTicks(7519),
                            Email = "Crystel30@gmail.com",
                            Password = "T0Q0q32/IBRs9LWYRC87YMjhYaDk2BxXSmmKNRz0Saw=",
                            Salt = "k//3zbGQWtJqQRdHXk9ulbqS9kIv2bjWimf08ui+nMs=",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 956, DateTimeKind.Local).AddTicks(7647),
                            UserName = "Jamaal97"
                        },
                        new
                        {
                            Id = 11,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 969, DateTimeKind.Local).AddTicks(7553),
                            Email = "Cody_Turcotte@yahoo.com",
                            Password = "egGQ5DezPHZ30ORhplwqUOUWKXvNbM1jtHTGRXu+iX8=",
                            Salt = "G7npn5ptkL5J8U2OXypmNiLuYLfSKsCJ/Nq+QNC9Lj0=",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 969, DateTimeKind.Local).AddTicks(7704),
                            UserName = "Clyde.Rohan31"
                        },
                        new
                        {
                            Id = 12,
                            AvatarId = 8,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 981, DateTimeKind.Local).AddTicks(4040),
                            Email = "Breana_Koss@gmail.com",
                            Password = "z2+XaJfVE8N2gxFHRtZZKeb4kfPkHxGx8+fInGxhtco=",
                            Salt = "LkVR8MKHoGAyyPT9WwuG1HEqevqugw06VKx5Z5HqZEk=",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 981, DateTimeKind.Local).AddTicks(4191),
                            UserName = "Baby.Mann42"
                        },
                        new
                        {
                            Id = 13,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 995, DateTimeKind.Local).AddTicks(9001),
                            Email = "Prudence76@yahoo.com",
                            Password = "13LiukA+R+Ev2KvavOjeKV9bkhi0NXpxJBUH+xctVyQ=",
                            Salt = "u2dbwqAn1V7fcfv/woWs2ZJ9mvMFuQy8mtUJ27a6HqI=",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 12, 995, DateTimeKind.Local).AddTicks(9134),
                            UserName = "Elmira_Bogan91"
                        },
                        new
                        {
                            Id = 14,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 19, DateTimeKind.Local).AddTicks(1559),
                            Email = "Norwood.Crooks@hotmail.com",
                            Password = "o/WO8niYhLtuhjZvhHPQOv/7IVheZxSXnbl6R4Ok4UE=",
                            Salt = "ErYKGbCDDAqkA3bC4mqQDUOzk7xsSwlbJibKLkARvsc=",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 19, DateTimeKind.Local).AddTicks(1686),
                            UserName = "Kayley.OConnell"
                        },
                        new
                        {
                            Id = 15,
                            AvatarId = 6,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 32, DateTimeKind.Local).AddTicks(7924),
                            Email = "Dixie.Kutch@yahoo.com",
                            Password = "6j5/IajUZkejL/tC4237Fe6g28rHLvnqHKaar8sAfPY=",
                            Salt = "kq0iAT8gze/5dMy/dPeMS1Jv7UUBY2DlXwn8g3MbYXU=",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 32, DateTimeKind.Local).AddTicks(8050),
                            UserName = "Karl.Daugherty48"
                        },
                        new
                        {
                            Id = 16,
                            AvatarId = 17,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 46, DateTimeKind.Local).AddTicks(2424),
                            Email = "Piper_Romaguera6@gmail.com",
                            Password = "rpJjTdhtgBj2Vi2rhg0QxF1kLfx6C3MLFBcLkfZTL5s=",
                            Salt = "8u9WILwmUgcsqdMnmRFvaV6Nq5ThzdZ/fLj1jcezr8g=",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 46, DateTimeKind.Local).AddTicks(2575),
                            UserName = "Alexandra_Ortiz"
                        },
                        new
                        {
                            Id = 17,
                            AvatarId = 6,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 61, DateTimeKind.Local).AddTicks(8350),
                            Email = "Otha23@hotmail.com",
                            Password = "w5dffNLAwrXTH/SATkwNRIoOBRvoZsblJUvkPmesfaI=",
                            Salt = "a4FNOnGq+goXpR9aNPLE1gfMGHbiQ75ONZfNjV8gd8g=",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 61, DateTimeKind.Local).AddTicks(8496),
                            UserName = "Linnie_Ziemann"
                        },
                        new
                        {
                            Id = 18,
                            AvatarId = 20,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 78, DateTimeKind.Local).AddTicks(9177),
                            Email = "Zachary_Daugherty6@gmail.com",
                            Password = "0YarHEvV57cN9TlaN+mFh5zQ0ZnwZStX5zapq2C6qH4=",
                            Salt = "20YTIJIofO1ZdcoRguq4n2D6vNGP6NkSNhNrngNoPc4=",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 78, DateTimeKind.Local).AddTicks(9327),
                            UserName = "Valerie.Feeney"
                        },
                        new
                        {
                            Id = 19,
                            AvatarId = 4,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 95, DateTimeKind.Local).AddTicks(3391),
                            Email = "Alva.Daugherty@yahoo.com",
                            Password = "SFReEAAHppEoP1O7VWXLht9p9o2dNcaTUi9bwvSrHac=",
                            Salt = "de8PfLSdQ62mSj0nbgQEOKJljkC4b/LHRoPWoYyO2uw=",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 95, DateTimeKind.Local).AddTicks(3535),
                            UserName = "Guy.Monahan"
                        },
                        new
                        {
                            Id = 20,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 113, DateTimeKind.Local).AddTicks(8572),
                            Email = "Jacynthe82@yahoo.com",
                            Password = "kCbtKbdSFzARnFd/3ZP28iN7psz+51GjzuTwqU0jfQw=",
                            Salt = "3CuRpGlzGiJaQq1Wv6JowmWz2iqC7/4E2qm/uOWX2kQ=",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 113, DateTimeKind.Local).AddTicks(8700),
                            UserName = "Haylie_Homenick"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 128, DateTimeKind.Local).AddTicks(5419),
                            Email = "test@gmail.com",
                            Password = "P0CiN0wQ3qMRDF0KSKCq+AnpJtpM4Hz2jY+NUV/qLRE=",
                            Salt = "SeHiMl5lTfaUfjnoFIGtW/eUVeAksnI7IQyfdfUWeyI=",
                            UpdatedAt = new DateTime(2021, 6, 4, 13, 11, 13, 128, DateTimeKind.Local).AddTicks(5419),
                            UserName = "testUser"
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Preview")
                        .WithMany()
                        .HasForeignKey("PreviewId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");

                    b.Navigation("Preview");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });
#pragma warning restore 612, 618
        }
    }
}
