// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thread_.NET.DAL.Context;

namespace Thread_.NET.DAL.Migrations
{
    [DbContext(typeof(ThreadContext))]
    [Migration("20210604075122_SomeMigration")]
    partial class SomeMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 20,
                            Body = "Voluptas eos amet et nihil omnis cum ut voluptatem.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 605, DateTimeKind.Local).AddTicks(4079),
                            PostId = 10,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 605, DateTimeKind.Local).AddTicks(6335)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 3,
                            Body = "Illo beatae voluptates est.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 605, DateTimeKind.Local).AddTicks(8348),
                            PostId = 4,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 605, DateTimeKind.Local).AddTicks(8382)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 11,
                            Body = "Quos incidunt voluptatem.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 605, DateTimeKind.Local).AddTicks(8570),
                            PostId = 20,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 605, DateTimeKind.Local).AddTicks(8586)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 19,
                            Body = "Earum nostrum harum eos et.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 605, DateTimeKind.Local).AddTicks(8734),
                            PostId = 11,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 605, DateTimeKind.Local).AddTicks(8748)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 7,
                            Body = "Qui voluptas est aut illo quasi consequatur.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 605, DateTimeKind.Local).AddTicks(8907),
                            PostId = 10,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 605, DateTimeKind.Local).AddTicks(8925)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 14,
                            Body = "Laudantium nam est eos architecto et explicabo doloribus.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 605, DateTimeKind.Local).AddTicks(9098),
                            PostId = 15,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 605, DateTimeKind.Local).AddTicks(9116)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 5,
                            Body = "Dolorum et commodi.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 605, DateTimeKind.Local).AddTicks(9370),
                            PostId = 12,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 605, DateTimeKind.Local).AddTicks(9393)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 13,
                            Body = "Corrupti quae eaque cupiditate aperiam hic.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 605, DateTimeKind.Local).AddTicks(9585),
                            PostId = 7,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 605, DateTimeKind.Local).AddTicks(9603)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 7,
                            Body = "Modi quas et beatae alias consectetur assumenda rem aperiam.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 605, DateTimeKind.Local).AddTicks(9781),
                            PostId = 13,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 605, DateTimeKind.Local).AddTicks(9801)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 7,
                            Body = "Eius eum assumenda excepturi et et totam aut quo.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 606, DateTimeKind.Local).AddTicks(1),
                            PostId = 18,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 606, DateTimeKind.Local).AddTicks(22)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 15,
                            Body = "Officia occaecati aliquam nihil sequi molestiae.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 606, DateTimeKind.Local).AddTicks(182),
                            PostId = 3,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 606, DateTimeKind.Local).AddTicks(202)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 7,
                            Body = "Voluptatem culpa officia molestiae similique qui ut at qui.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 606, DateTimeKind.Local).AddTicks(379),
                            PostId = 19,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 606, DateTimeKind.Local).AddTicks(399)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 19,
                            Body = "Soluta ut numquam enim perferendis autem voluptatem aut numquam eaque.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 606, DateTimeKind.Local).AddTicks(786),
                            PostId = 13,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 606, DateTimeKind.Local).AddTicks(814)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 11,
                            Body = "Quos deleniti recusandae ut voluptatem est culpa.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 606, DateTimeKind.Local).AddTicks(993),
                            PostId = 20,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 606, DateTimeKind.Local).AddTicks(1013)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 11,
                            Body = "Magnam dolor officia tempore architecto similique quaerat sunt asperiores rerum.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 606, DateTimeKind.Local).AddTicks(1210),
                            PostId = 19,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 606, DateTimeKind.Local).AddTicks(1232)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 1,
                            Body = "Ipsa voluptatem eos harum error.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 606, DateTimeKind.Local).AddTicks(1501),
                            PostId = 13,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 606, DateTimeKind.Local).AddTicks(1619)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 21,
                            Body = "Cum sapiente laboriosam beatae magnam.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 606, DateTimeKind.Local).AddTicks(1833),
                            PostId = 11,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 606, DateTimeKind.Local).AddTicks(1852)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 2,
                            Body = "Quisquam ut corrupti optio quis delectus explicabo molestiae sed.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 606, DateTimeKind.Local).AddTicks(2118),
                            PostId = 11,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 606, DateTimeKind.Local).AddTicks(2138)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 1,
                            Body = "Laudantium et soluta vitae culpa tempora saepe adipisci sit aut.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 606, DateTimeKind.Local).AddTicks(2302),
                            PostId = 10,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 606, DateTimeKind.Local).AddTicks(2320)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 13,
                            Body = "Laborum sunt eius dolore mollitia dolorem.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 606, DateTimeKind.Local).AddTicks(2456),
                            PostId = 16,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 606, DateTimeKind.Local).AddTicks(2475)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("CommentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentId = 4,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(450),
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(2421),
                            UserId = 15
                        },
                        new
                        {
                            Id = 2,
                            CommentId = 5,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(3940),
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(3963),
                            UserId = 21
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 3,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(4061),
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(4074),
                            UserId = 10
                        },
                        new
                        {
                            Id = 4,
                            CommentId = 4,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(4191),
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(4202),
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            CommentId = 6,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(4278),
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(4290),
                            UserId = 15
                        },
                        new
                        {
                            Id = 6,
                            CommentId = 6,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(4362),
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(4374),
                            UserId = 4
                        },
                        new
                        {
                            Id = 7,
                            CommentId = 12,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(4453),
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(4467),
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            CommentId = 19,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(4538),
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(4552),
                            UserId = 13
                        },
                        new
                        {
                            Id = 9,
                            CommentId = 10,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(4621),
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(4633),
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            CommentId = 13,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(4703),
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(4716),
                            UserId = 17
                        },
                        new
                        {
                            Id = 11,
                            CommentId = 2,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(4785),
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(4797),
                            UserId = 18
                        },
                        new
                        {
                            Id = 12,
                            CommentId = 3,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(4864),
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(4875),
                            UserId = 5
                        },
                        new
                        {
                            Id = 13,
                            CommentId = 10,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(4943),
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(4955),
                            UserId = 20
                        },
                        new
                        {
                            Id = 14,
                            CommentId = 6,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(5024),
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(5037),
                            UserId = 10
                        },
                        new
                        {
                            Id = 15,
                            CommentId = 15,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(5110),
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(5121),
                            UserId = 14
                        },
                        new
                        {
                            Id = 16,
                            CommentId = 3,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(5190),
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(5201),
                            UserId = 21
                        },
                        new
                        {
                            Id = 17,
                            CommentId = 19,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(5268),
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(5279),
                            UserId = 6
                        },
                        new
                        {
                            Id = 18,
                            CommentId = 20,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(5350),
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(5363),
                            UserId = 10
                        },
                        new
                        {
                            Id = 19,
                            CommentId = 2,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(5433),
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(5445),
                            UserId = 4
                        },
                        new
                        {
                            Id = 20,
                            CommentId = 12,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(5513),
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 648, DateTimeKind.Local).AddTicks(5524),
                            UserId = 8
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 993, DateTimeKind.Local).AddTicks(1557),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/832.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(2772)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(4919),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/563.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(4960)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(5059),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/477.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(5071)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(5127),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/649.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(5139)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(5194),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1033.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(5208)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(5264),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/567.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(5278)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(5337),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1174.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(5350)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(5410),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/840.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(5423)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(5483),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/564.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(5500)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(5598),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/580.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(5611)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(5667),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/643.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(5679)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(5733),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/265.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(5745)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(5798),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1050.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(5810)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(5863),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/771.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(5875)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(5934),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/425.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(5946)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(6001),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/122.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(6013)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(6072),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1023.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(6088)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(6146),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/837.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(6161)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(6218),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/843.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(6231)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(6291),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1218.jpg",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 19, 994, DateTimeKind.Local).AddTicks(6304)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(677),
                            URL = "https://picsum.photos/640/480/?image=1027",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(2644)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(3254),
                            URL = "https://picsum.photos/640/480/?image=401",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(3276)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(3366),
                            URL = "https://picsum.photos/640/480/?image=688",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(3381)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(3444),
                            URL = "https://picsum.photos/640/480/?image=191",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(3458)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(3528),
                            URL = "https://picsum.photos/640/480/?image=556",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(3544)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(3613),
                            URL = "https://picsum.photos/640/480/?image=945",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(3630)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(3703),
                            URL = "https://picsum.photos/640/480/?image=948",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(3716)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(7407),
                            URL = "https://picsum.photos/640/480/?image=620",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(7431)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(7523),
                            URL = "https://picsum.photos/640/480/?image=988",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(7534)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(7590),
                            URL = "https://picsum.photos/640/480/?image=509",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(7602)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(7692),
                            URL = "https://picsum.photos/640/480/?image=964",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(7708)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(7778),
                            URL = "https://picsum.photos/640/480/?image=991",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(7792)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(7856),
                            URL = "https://picsum.photos/640/480/?image=955",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(7869)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(7933),
                            URL = "https://picsum.photos/640/480/?image=736",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(7948)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(8009),
                            URL = "https://picsum.photos/640/480/?image=775",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(8022)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(8077),
                            URL = "https://picsum.photos/640/480/?image=114",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(8091)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(8154),
                            URL = "https://picsum.photos/640/480/?image=270",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(8169)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(8233),
                            URL = "https://picsum.photos/640/480/?image=672",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(8247)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(8313),
                            URL = "https://picsum.photos/640/480/?image=570",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(8328)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(8392),
                            URL = "https://picsum.photos/640/480/?image=463",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 9, DateTimeKind.Local).AddTicks(8404)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PreviewId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PreviewId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 7,
                            Body = "ea",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 571, DateTimeKind.Local).AddTicks(6610),
                            PreviewId = 38,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 571, DateTimeKind.Local).AddTicks(8684)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 15,
                            Body = "Consectetur aspernatur et ut rerum voluptas quasi ut molestias.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 582, DateTimeKind.Local).AddTicks(4795),
                            PreviewId = 30,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 582, DateTimeKind.Local).AddTicks(4953)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 7,
                            Body = "Cupiditate optio voluptas est similique sint velit.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 582, DateTimeKind.Local).AddTicks(6119),
                            PreviewId = 40,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 582, DateTimeKind.Local).AddTicks(6151)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 5,
                            Body = "ea",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 582, DateTimeKind.Local).AddTicks(6344),
                            PreviewId = 25,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 582, DateTimeKind.Local).AddTicks(6361)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 17,
                            Body = "Fuga dolores perferendis nam omnis sapiente quia accusantium. Necessitatibus quia aut aut ut quia fugiat dolore veritatis magnam. Reprehenderit quo sit quis. Debitis necessitatibus dicta eos. Quo repellendus velit eius aut sapiente tempore vel eos. Sunt illum libero cum maxime modi rerum.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 584, DateTimeKind.Local).AddTicks(2444),
                            PreviewId = 27,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 584, DateTimeKind.Local).AddTicks(2583)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 11,
                            Body = "Qui nobis quis repudiandae.\nFacilis odio rerum architecto.\nRerum numquam dolor.\nOmnis aut sunt dolore nesciunt iusto.\nEst et in quae.\nFuga alias doloribus iste veniam laborum consequatur sed.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 584, DateTimeKind.Local).AddTicks(6312),
                            PreviewId = 22,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 584, DateTimeKind.Local).AddTicks(6386)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 12,
                            Body = "Accusantium autem reiciendis corrupti provident non qui et ex. Alias labore iste consequatur cupiditate aut. Et quo accusamus. Sit iusto saepe sint facere ad voluptate. Sit voluptatem tenetur quia qui dolores inventore modi. Vitae est mollitia voluptatem.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 584, DateTimeKind.Local).AddTicks(7224),
                            PreviewId = 26,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 584, DateTimeKind.Local).AddTicks(7255)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 19,
                            Body = "Et quis error perferendis ducimus eius aut minima. Itaque vitae aut. Et ipsa eos accusantium amet ab sed odit ut. Placeat nulla maiores veritatis enim commodi.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 584, DateTimeKind.Local).AddTicks(8014),
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 584, DateTimeKind.Local).AddTicks(8047)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 12,
                            Body = "Aperiam quia beatae. Illum minus voluptatem ipsum magni. Qui modi corporis.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 584, DateTimeKind.Local).AddTicks(8430),
                            PreviewId = 40,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 584, DateTimeKind.Local).AddTicks(8457)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 18,
                            Body = "Consequatur earum velit et.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 584, DateTimeKind.Local).AddTicks(8674),
                            PreviewId = 21,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 584, DateTimeKind.Local).AddTicks(8700)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 2,
                            Body = "Sequi eum repudiandae quaerat ab dolor. Placeat et et dolor impedit quis ipsam aspernatur recusandae. Laboriosam est dolorum.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 584, DateTimeKind.Local).AddTicks(9450),
                            PreviewId = 34,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 584, DateTimeKind.Local).AddTicks(9485)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 2,
                            Body = "Occaecati sapiente repellat velit accusantium ullam voluptatem.\nEx in consectetur aliquam.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 584, DateTimeKind.Local).AddTicks(9804),
                            PreviewId = 38,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 584, DateTimeKind.Local).AddTicks(9831)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 12,
                            Body = "Autem et molestias sed repellat fuga aut. Ut atque quia omnis dolor dicta odit voluptas. Provident numquam omnis suscipit deserunt fuga occaecati similique perferendis. Et soluta ut ut facilis ipsum consequuntur eligendi.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 585, DateTimeKind.Local).AddTicks(457),
                            PreviewId = 22,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 585, DateTimeKind.Local).AddTicks(490)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 19,
                            Body = "Eveniet minus quia vel inventore. In corrupti dicta esse fugit sed placeat. Eius repellendus consequatur doloribus ut voluptatibus aut adipisci. Libero eius natus. Et qui perferendis ad autem aut.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 585, DateTimeKind.Local).AddTicks(1142),
                            PreviewId = 38,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 585, DateTimeKind.Local).AddTicks(1172)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 21,
                            Body = "Laudantium reiciendis odio aliquam qui ut sed qui eveniet.\nEt et dicta culpa asperiores ut.\nCumque qui qui deserunt dolores quia.\nSunt quasi eos quia non accusamus autem et ipsam adipisci.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 585, DateTimeKind.Local).AddTicks(1633),
                            PreviewId = 31,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 585, DateTimeKind.Local).AddTicks(1660)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 13,
                            Body = "Id unde corrupti nam aut placeat.\nNon optio quibusdam rem nihil dolor.\nPerferendis eius delectus assumenda occaecati neque placeat consequuntur quibusdam.\nDoloremque impedit nostrum deserunt.\nIllo consequatur repellat eum voluptas asperiores ut odit eum voluptas.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 585, DateTimeKind.Local).AddTicks(2481),
                            PreviewId = 24,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 585, DateTimeKind.Local).AddTicks(2514)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 2,
                            Body = "dignissimos",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 585, DateTimeKind.Local).AddTicks(2684),
                            PreviewId = 31,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 585, DateTimeKind.Local).AddTicks(2706)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 13,
                            Body = "Quod ullam aut natus modi voluptatem laudantium.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 585, DateTimeKind.Local).AddTicks(3046),
                            PreviewId = 33,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 585, DateTimeKind.Local).AddTicks(3078)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 15,
                            Body = "Quia praesentium eveniet aperiam facilis temporibus rem mollitia. Aut aut aut dolores dignissimos ut error id nobis. Ratione culpa explicabo unde nostrum. Quos repellendus reiciendis commodi cumque eum voluptatem qui adipisci sequi.",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 585, DateTimeKind.Local).AddTicks(3535),
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 585, DateTimeKind.Local).AddTicks(3563)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 13,
                            Body = "quibusdam",
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 585, DateTimeKind.Local).AddTicks(3814),
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 585, DateTimeKind.Local).AddTicks(3842)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("PostId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PostReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 630, DateTimeKind.Local).AddTicks(5496),
                            IsLike = false,
                            PostId = 13,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 630, DateTimeKind.Local).AddTicks(7712),
                            UserId = 6
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 630, DateTimeKind.Local).AddTicks(9542),
                            IsLike = true,
                            PostId = 18,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 630, DateTimeKind.Local).AddTicks(9581),
                            UserId = 5
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 630, DateTimeKind.Local).AddTicks(9711),
                            IsLike = true,
                            PostId = 15,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 630, DateTimeKind.Local).AddTicks(9726),
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 630, DateTimeKind.Local).AddTicks(9814),
                            IsLike = false,
                            PostId = 10,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 630, DateTimeKind.Local).AddTicks(9829),
                            UserId = 11
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 630, DateTimeKind.Local).AddTicks(9914),
                            IsLike = false,
                            PostId = 16,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 630, DateTimeKind.Local).AddTicks(9928),
                            UserId = 18
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(10),
                            IsLike = true,
                            PostId = 10,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(25),
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(112),
                            IsLike = true,
                            PostId = 7,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(126),
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(209),
                            IsLike = false,
                            PostId = 7,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(223),
                            UserId = 16
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(309),
                            IsLike = true,
                            PostId = 16,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(324),
                            UserId = 7
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(408),
                            IsLike = true,
                            PostId = 4,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(423),
                            UserId = 19
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(503),
                            IsLike = false,
                            PostId = 19,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(517),
                            UserId = 6
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(600),
                            IsLike = true,
                            PostId = 13,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(615),
                            UserId = 15
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(699),
                            IsLike = true,
                            PostId = 8,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(713),
                            UserId = 2
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(798),
                            IsLike = true,
                            PostId = 3,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(816),
                            UserId = 18
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(898),
                            IsLike = true,
                            PostId = 11,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(911),
                            UserId = 10
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(1154),
                            IsLike = true,
                            PostId = 16,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(1177),
                            UserId = 16
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(1273),
                            IsLike = false,
                            PostId = 20,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(1288),
                            UserId = 20
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(1383),
                            IsLike = true,
                            PostId = 11,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(1398),
                            UserId = 17
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(1512),
                            IsLike = true,
                            PostId = 11,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(1528),
                            UserId = 3
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(1620),
                            IsLike = true,
                            PostId = 18,
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 631, DateTimeKind.Local).AddTicks(1636),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AvatarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 5,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 130, DateTimeKind.Local).AddTicks(8011),
                            Email = "Talon71@gmail.com",
                            Password = "TCOSYbZK0h/j/7Bxil1iipS2YsirCC7f7eQvWrIDejM=",
                            Salt = "Rf46XRfv9MS+fegU7NyAeEWs4orqHT6bAXvPQDtlu3I=",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 131, DateTimeKind.Local).AddTicks(272),
                            UserName = "Cheyenne.Ryan"
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 1,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 150, DateTimeKind.Local).AddTicks(3017),
                            Email = "Celia95@hotmail.com",
                            Password = "volK6ocRq5rbgk6X9mdqVMjwRDyU/WQTZ2SOsM0D0Yg=",
                            Salt = "IuADl9ufwa7Ejsw88opZeoAmrSP6m/PpFwoy/7bOpho=",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 150, DateTimeKind.Local).AddTicks(3174),
                            UserName = "Rosetta24"
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 171, DateTimeKind.Local).AddTicks(5365),
                            Email = "Candelario.Kshlerin51@gmail.com",
                            Password = "KsBLCCIiUSxx4Gh7/EPLFC/5gDQ0sD1MysiTJG1fJCw=",
                            Salt = "Q14OIS+Rb5cc571eRqWhIbuAlkj4r9AN2to64je3uLQ=",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 171, DateTimeKind.Local).AddTicks(5511),
                            UserName = "Keely_Vandervort"
                        },
                        new
                        {
                            Id = 4,
                            AvatarId = 5,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 202, DateTimeKind.Local).AddTicks(5610),
                            Email = "Gregorio26@yahoo.com",
                            Password = "b6fnj+BI7597xyxpvPcvbH2CBlS/Oo+KuIBYiu1EfFM=",
                            Salt = "QNwHPI3i9lpvDaXq4GJYiYgs2gulsxlAntr+fTF9CQw=",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 202, DateTimeKind.Local).AddTicks(5761),
                            UserName = "Zander_Kub58"
                        },
                        new
                        {
                            Id = 5,
                            AvatarId = 4,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 217, DateTimeKind.Local).AddTicks(6821),
                            Email = "Kennedy.Stark66@hotmail.com",
                            Password = "nJ/LGLSYuHotiW7h1FsOHqN29cBnUZAMbFJuyN588jY=",
                            Salt = "gp+lc8gesI/29RQLs5UsHYW6cz5MDyHW5CLkxUHVz20=",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 217, DateTimeKind.Local).AddTicks(6950),
                            UserName = "Callie48"
                        },
                        new
                        {
                            Id = 6,
                            AvatarId = 15,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 229, DateTimeKind.Local).AddTicks(9988),
                            Email = "Emie_Padberg67@yahoo.com",
                            Password = "86v1OeQqxzwb1Cr/av+ffxchqLD5r3vZUiPM8O2kYjo=",
                            Salt = "t+GzFx4mRH3BHF3N7G566zxNZo9UERzNjlrFsWJgFSk=",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 230, DateTimeKind.Local).AddTicks(125),
                            UserName = "Juston37"
                        },
                        new
                        {
                            Id = 7,
                            AvatarId = 16,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 242, DateTimeKind.Local).AddTicks(520),
                            Email = "Corine51@gmail.com",
                            Password = "rfJ24youUfh74FOKHzleuCm1Hh5rzwsbynbIN1J+KSQ=",
                            Salt = "1PFAbAy/pTnNckhgx3mKUE9fyYw6Y/9lkq4Kffi3iP4=",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 242, DateTimeKind.Local).AddTicks(652),
                            UserName = "Tracey.Boyer"
                        },
                        new
                        {
                            Id = 8,
                            AvatarId = 13,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 255, DateTimeKind.Local).AddTicks(9171),
                            Email = "Johan_Gusikowski39@gmail.com",
                            Password = "fUpEzWbZHOHy3TxIEjsgz29B3j/sYzFRBGY2kjaX3KA=",
                            Salt = "/MtXtwrxvQ6xrOmTS/VyCtq2W694Oq0Zl+nPFYO7mX8=",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 255, DateTimeKind.Local).AddTicks(9318),
                            UserName = "Brielle.Brown"
                        },
                        new
                        {
                            Id = 9,
                            AvatarId = 8,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 273, DateTimeKind.Local).AddTicks(9041),
                            Email = "Antonina.Turner@yahoo.com",
                            Password = "dv/m5G6w0nPN4UJnWtMnn2alNZA4H6H/dKthCzBjl+A=",
                            Salt = "Co+7w67D6CwBK1N13AO0KU4hE2HZvF1Lhlq/jgWwAwc=",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 273, DateTimeKind.Local).AddTicks(9197),
                            UserName = "Ashtyn_Blanda49"
                        },
                        new
                        {
                            Id = 10,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 290, DateTimeKind.Local).AddTicks(5534),
                            Email = "Ignacio_Nikolaus@gmail.com",
                            Password = "R8sSbusycZNRPMUnLTWCTXHuNbSQP/Gi6U32jxNeJh8=",
                            Salt = "YlPjSbaYPgFb4NFGVA3eFUetLEJeXR/2qUo6DYxuloM=",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 290, DateTimeKind.Local).AddTicks(5679),
                            UserName = "Lizeth_Quitzon"
                        },
                        new
                        {
                            Id = 11,
                            AvatarId = 5,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 309, DateTimeKind.Local).AddTicks(4117),
                            Email = "Janessa.Ernser@yahoo.com",
                            Password = "AlVA5VoBeiFvVlfsCvBfxGesdczn7CpFeWkI0v0wU+4=",
                            Salt = "OnJGrlI4q2exzyeFMd2k8ZFdN9FDADzB/6NcqOz8vCM=",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 309, DateTimeKind.Local).AddTicks(4264),
                            UserName = "Jarrell28"
                        },
                        new
                        {
                            Id = 12,
                            AvatarId = 2,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 329, DateTimeKind.Local).AddTicks(4276),
                            Email = "Fredy25@yahoo.com",
                            Password = "lDODMBemV/9CR5qfd8As4WdAGeIz2HscFeIAh1g9G1M=",
                            Salt = "8xjv9IEGITySdXc4KF0oh20MwGLKpEsebzy2SZM6yAg=",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 329, DateTimeKind.Local).AddTicks(4453),
                            UserName = "Elmer_Connelly79"
                        },
                        new
                        {
                            Id = 13,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 347, DateTimeKind.Local).AddTicks(1225),
                            Email = "Justyn87@hotmail.com",
                            Password = "rIQBtjvByHYEhuScfTOZnFbPpAlW7AJ3prNgjvyrijc=",
                            Salt = "v3wDNh/MdjLLZ+fXiFBSOuDTSmpTGfJp0IXT0eZyTX4=",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 347, DateTimeKind.Local).AddTicks(1389),
                            UserName = "Guiseppe.Maggio28"
                        },
                        new
                        {
                            Id = 14,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 364, DateTimeKind.Local).AddTicks(2271),
                            Email = "Delpha_Treutel@hotmail.com",
                            Password = "ZLUoT+YpCS327CAkU0Bek3Oya3Ygmpwt2B/sq6TdNMk=",
                            Salt = "CBtjoJ988sewDNtfIGtPXhfy2wDdjXkUcxB/TjJVIBQ=",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 364, DateTimeKind.Local).AddTicks(2438),
                            UserName = "Gavin.Bins19"
                        },
                        new
                        {
                            Id = 15,
                            AvatarId = 8,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 381, DateTimeKind.Local).AddTicks(7796),
                            Email = "Stone_Miller94@yahoo.com",
                            Password = "YMj2TxJsTYlZ+uHHl7p7WSwX0IaqZglsLYaYEzvGu9o=",
                            Salt = "3Zjj2SXQCwfkvo15qIkvv1hIz2lDtYPKlrhck6FdZeM=",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 381, DateTimeKind.Local).AddTicks(8024),
                            UserName = "Chris44"
                        },
                        new
                        {
                            Id = 16,
                            AvatarId = 12,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 405, DateTimeKind.Local).AddTicks(6280),
                            Email = "Deontae_Harris46@gmail.com",
                            Password = "5aY0vhWy/SuXgHB92SWCgRWxaC7n+tPKBS0IVkptqX4=",
                            Salt = "b1jqe3gMFXHKHMgN3373qjk8Jzb7SmehxIwjk+MKggk=",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 405, DateTimeKind.Local).AddTicks(6456),
                            UserName = "Kaela_Langosh"
                        },
                        new
                        {
                            Id = 17,
                            AvatarId = 16,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 424, DateTimeKind.Local).AddTicks(3289),
                            Email = "Janae_Ryan96@yahoo.com",
                            Password = "fYaasPcSAn+wh4ILRH7VwThBWAARc9XmLq3z8XcsJKA=",
                            Salt = "Ago5aX0SyfYt3EWPXycjvP5eIly8r0qf4yfbg4JGOEM=",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 424, DateTimeKind.Local).AddTicks(3472),
                            UserName = "Magdalen_Gaylord39"
                        },
                        new
                        {
                            Id = 18,
                            AvatarId = 17,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 444, DateTimeKind.Local).AddTicks(5220),
                            Email = "Kayden_Leffler45@gmail.com",
                            Password = "r/4lfZLa9ScAd0I6cNi7Pp6dNX9EvpOKBbM6udx55qE=",
                            Salt = "26yi1o8O6I1gP2kgco/oJPlkaQk/rExcERA78Mo+GLE=",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 444, DateTimeKind.Local).AddTicks(5401),
                            UserName = "Clemens85"
                        },
                        new
                        {
                            Id = 19,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 462, DateTimeKind.Local).AddTicks(8079),
                            Email = "Rubye.Witting89@yahoo.com",
                            Password = "dZdEQqUcpeu37QP84/Gp6qUCTf+72ce5a15QEhERPW8=",
                            Salt = "v6oT+nHjCFkEtgqUr+VvItCJf01xW2fvT2Me2FQ/p+4=",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 462, DateTimeKind.Local).AddTicks(8246),
                            UserName = "Lenna14"
                        },
                        new
                        {
                            Id = 20,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 501, DateTimeKind.Local).AddTicks(8825),
                            Email = "Thea_Romaguera98@hotmail.com",
                            Password = "mER/rfqlIOnh5PCuKJPUDhyWWVgrLSxhWwzOnFDAjL8=",
                            Salt = "kFM3mFxXGDp80/xzTO1/YBWL1AvniR5YJDB83d8Bsdc=",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 501, DateTimeKind.Local).AddTicks(8998),
                            UserName = "Deangelo_Zboncak87"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 520, DateTimeKind.Local).AddTicks(7089),
                            Email = "test@gmail.com",
                            Password = "hMYeteBbrjBNhRD8HL+Aozk+hE7TwpfypX8R1tpXtdc=",
                            Salt = "E5oNxCS5Nxp5F1SyDghP/5bZzsIdHxjv58/YnK1HP6U=",
                            UpdatedAt = new DateTime(2021, 6, 4, 10, 51, 20, 520, DateTimeKind.Local).AddTicks(7089),
                            UserName = "testUser"
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Preview")
                        .WithMany()
                        .HasForeignKey("PreviewId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");

                    b.Navigation("Preview");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });
#pragma warning restore 612, 618
        }
    }
}
