// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thread_.NET.DAL.Context;

namespace Thread_.NET.DAL.Migrations
{
    [DbContext(typeof(ThreadContext))]
    [Migration("20210612131627_IsDeleted2.0")]
    partial class IsDeleted20
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Body = "Hic aut nihil tempora.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(998),
                            IsDeleted = false,
                            PostId = 17,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(2010)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 20,
                            Body = "Suscipit facere voluptatem dolorem deleniti quisquam dolore ut at.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(3080),
                            IsDeleted = false,
                            PostId = 11,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(3099)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 18,
                            Body = "Dolorem officiis aut inventore deleniti soluta cupiditate eos ratione.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(3255),
                            IsDeleted = false,
                            PostId = 10,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(3265)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            Body = "Ea dolor eaque eos provident est ipsa.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(3584),
                            IsDeleted = false,
                            PostId = 10,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(3603)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 20,
                            Body = "Autem consequatur magnam explicabo.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(3714),
                            IsDeleted = false,
                            PostId = 5,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(3724)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 21,
                            Body = "Quidem saepe voluptas provident ipsa id quis qui.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(3907),
                            IsDeleted = false,
                            PostId = 19,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(3918)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 7,
                            Body = "Quas nobis impedit corrupti ullam nihil nihil.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(4105),
                            IsDeleted = false,
                            PostId = 14,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(4117)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 2,
                            Body = "Illum vitae et eum voluptas voluptatem.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(4222),
                            IsDeleted = false,
                            PostId = 17,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(4231)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 10,
                            Body = "Eum omnis ullam blanditiis molestias tenetur laborum veritatis ea.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(4351),
                            IsDeleted = false,
                            PostId = 16,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(4361)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 18,
                            Body = "In eum dolores est consequatur iusto nemo impedit.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(4597),
                            IsDeleted = false,
                            PostId = 14,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(4610)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 15,
                            Body = "Ut exercitationem qui vel recusandae voluptatem porro.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(4734),
                            IsDeleted = false,
                            PostId = 5,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(4744)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 5,
                            Body = "Ratione natus dolor sed tempora.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(4842),
                            IsDeleted = false,
                            PostId = 11,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(4852)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 16,
                            Body = "Ea veritatis eos non libero labore magnam voluptate.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(4961),
                            IsDeleted = false,
                            PostId = 11,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(4970)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 15,
                            Body = "Assumenda explicabo voluptatibus impedit qui omnis neque.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(5074),
                            IsDeleted = false,
                            PostId = 3,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(5083)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 10,
                            Body = "Repudiandae facilis est perspiciatis autem et ut porro.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(5344),
                            IsDeleted = false,
                            PostId = 12,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(5357)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 16,
                            Body = "Omnis voluptatem totam laborum.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(5464),
                            IsDeleted = false,
                            PostId = 13,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(5474)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 4,
                            Body = "Qui natus cupiditate esse velit consequuntur iusto dolore.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(5581),
                            IsDeleted = false,
                            PostId = 18,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(5590)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 9,
                            Body = "Dignissimos et excepturi iure consequatur ducimus esse dolores.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(5703),
                            IsDeleted = false,
                            PostId = 6,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(5712)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 9,
                            Body = "Voluptatibus eligendi quis itaque aliquid asperiores quasi sint explicabo.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(5831),
                            IsDeleted = false,
                            PostId = 4,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(5840)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 3,
                            Body = "Aut qui voluptatem dolores dignissimos animi odit.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(5943),
                            IsDeleted = false,
                            PostId = 6,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 814, DateTimeKind.Local).AddTicks(5952)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDislike")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("CommentId", "UserId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("UserId");

                    b.ToTable("CommentReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentId = 2,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 861, DateTimeKind.Local).AddTicks(9600),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(750),
                            UserId = 4
                        },
                        new
                        {
                            Id = 2,
                            CommentId = 19,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(2221),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(2273),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 1,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(2489),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(2505),
                            UserId = 5
                        },
                        new
                        {
                            Id = 4,
                            CommentId = 17,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(2605),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(2619),
                            UserId = 18
                        },
                        new
                        {
                            Id = 5,
                            CommentId = 3,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(2702),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(2715),
                            UserId = 18
                        },
                        new
                        {
                            Id = 6,
                            CommentId = 10,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(2797),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(2813),
                            UserId = 19
                        },
                        new
                        {
                            Id = 7,
                            CommentId = 2,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(2895),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(2908),
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            CommentId = 12,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(2994),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(3007),
                            UserId = 12
                        },
                        new
                        {
                            Id = 9,
                            CommentId = 13,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(3089),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(3104),
                            UserId = 15
                        },
                        new
                        {
                            Id = 10,
                            CommentId = 19,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(3203),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(3220),
                            UserId = 20
                        },
                        new
                        {
                            Id = 11,
                            CommentId = 9,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(3308),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(3321),
                            UserId = 13
                        },
                        new
                        {
                            Id = 12,
                            CommentId = 18,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(3403),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(3415),
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            CommentId = 14,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(3496),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(3509),
                            UserId = 15
                        },
                        new
                        {
                            Id = 14,
                            CommentId = 2,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(3601),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(3656),
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            CommentId = 11,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(3760),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(3776),
                            UserId = 3
                        },
                        new
                        {
                            Id = 16,
                            CommentId = 17,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(3862),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(3876),
                            UserId = 15
                        },
                        new
                        {
                            Id = 17,
                            CommentId = 17,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(3967),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(3981),
                            UserId = 10
                        },
                        new
                        {
                            Id = 18,
                            CommentId = 14,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(4206),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(4226),
                            UserId = 8
                        },
                        new
                        {
                            Id = 19,
                            CommentId = 13,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(4323),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(4337),
                            UserId = 17
                        },
                        new
                        {
                            Id = 20,
                            CommentId = 8,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(4420),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 862, DateTimeKind.Local).AddTicks(4432),
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 348, DateTimeKind.Local).AddTicks(3358),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/779.jpg",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(2714)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(3942),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1168.jpg",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(3957)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4006),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/837.jpg",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4014)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4047),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1221.jpg",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4054)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4086),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/406.jpg",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4094)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4125),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1101.jpg",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4133)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4405),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/762.jpg",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4413)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4449),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1107.jpg",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4457)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4490),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/102.jpg",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4497)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4529),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/752.jpg",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4537)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4568),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1155.jpg",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4576)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4607),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/175.jpg",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4615)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4646),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/480.jpg",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4654)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4685),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/871.jpg",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4692)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4724),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/229.jpg",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4731)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4763),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1227.jpg",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4771)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4802),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1187.jpg",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4810)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4841),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/388.jpg",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4849)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4880),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/182.jpg",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4888)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4919),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/114.jpg",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 349, DateTimeKind.Local).AddTicks(4927)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 361, DateTimeKind.Local).AddTicks(8958),
                            URL = "https://picsum.photos/640/480/?image=142",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 361, DateTimeKind.Local).AddTicks(9983)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(385),
                            URL = "https://picsum.photos/640/480/?image=432",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(397)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(435),
                            URL = "https://picsum.photos/640/480/?image=675",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(443)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(477),
                            URL = "https://picsum.photos/640/480/?image=1044",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(485)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(519),
                            URL = "https://picsum.photos/640/480/?image=716",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(527)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(559),
                            URL = "https://picsum.photos/640/480/?image=544",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(567)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(599),
                            URL = "https://picsum.photos/640/480/?image=862",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(607)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(639),
                            URL = "https://picsum.photos/640/480/?image=450",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(646)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(678),
                            URL = "https://picsum.photos/640/480/?image=34",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(850)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(939),
                            URL = "https://picsum.photos/640/480/?image=667",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(948)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(983),
                            URL = "https://picsum.photos/640/480/?image=253",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(991)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(1025),
                            URL = "https://picsum.photos/640/480/?image=731",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(1033)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(1067),
                            URL = "https://picsum.photos/640/480/?image=286",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(1075)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(1109),
                            URL = "https://picsum.photos/640/480/?image=577",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(1117)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(1150),
                            URL = "https://picsum.photos/640/480/?image=656",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(1158)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(1191),
                            URL = "https://picsum.photos/640/480/?image=568",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(1199)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(1232),
                            URL = "https://picsum.photos/640/480/?image=806",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(1240)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(1272),
                            URL = "https://picsum.photos/640/480/?image=1032",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(1280)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(1313),
                            URL = "https://picsum.photos/640/480/?image=183",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(1321)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(1355),
                            URL = "https://picsum.photos/640/480/?image=477",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 362, DateTimeKind.Local).AddTicks(1363)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("PreviewId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PreviewId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 4,
                            Body = "Ducimus voluptate consequuntur officiis quia.\nSequi ipsa soluta rem rem exercitationem reiciendis fuga provident.\nLaudantium tempora ipsum sint cum sunt dolor ipsum.\nAmet non quo fugiat nisi qui molestiae.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 797, DateTimeKind.Local).AddTicks(4413),
                            IsDeleted = false,
                            PreviewId = 32,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 797, DateTimeKind.Local).AddTicks(6094)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 21,
                            Body = "Quidem vero nam voluptatum omnis soluta voluptatem facere et.\nEt qui qui nostrum rerum quos qui.\nEa et a nemo eos distinctio dignissimos quia.\nVoluptas ipsa quo vel aperiam.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 797, DateTimeKind.Local).AddTicks(9168),
                            IsDeleted = false,
                            PreviewId = 22,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 797, DateTimeKind.Local).AddTicks(9208)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 21,
                            Body = "Dignissimos repudiandae velit harum quam et et. Necessitatibus eum illo aliquam itaque repellat dolores incidunt. Et sit quisquam consequatur doloremque omnis nisi qui impedit. Quisquam totam maxime totam laudantium sint maiores eos facere.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 798, DateTimeKind.Local).AddTicks(2356),
                            IsDeleted = false,
                            PreviewId = 40,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 798, DateTimeKind.Local).AddTicks(2403)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            Body = "Rerum omnis dolorem veniam architecto odit.\nVoluptatem aut aliquam sit dolores et et esse.\nEt consequatur impedit ad recusandae.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 798, DateTimeKind.Local).AddTicks(2925),
                            IsDeleted = false,
                            PreviewId = 25,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 798, DateTimeKind.Local).AddTicks(2950)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 12,
                            Body = "Tenetur eos quod minima eum voluptatem sunt ut. Voluptatum est veritatis. Id architecto ea distinctio corrupti veniam ut et. Est reprehenderit aut amet eum delectus. Cumque voluptate repudiandae eligendi suscipit sequi at.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 798, DateTimeKind.Local).AddTicks(3762),
                            IsDeleted = false,
                            PreviewId = 32,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 798, DateTimeKind.Local).AddTicks(3807)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 14,
                            Body = "Voluptate esse odio itaque harum consequatur veritatis aut velit provident.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 798, DateTimeKind.Local).AddTicks(5528),
                            IsDeleted = false,
                            PreviewId = 32,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 798, DateTimeKind.Local).AddTicks(5568)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 17,
                            Body = "Laudantium dolores ut qui rerum et consequuntur nobis ea.\nVel consequatur esse.\nModi dolorem dolores veritatis commodi error.\nQuae temporibus possimus debitis consequuntur est.\nSit sed placeat veniam architecto praesentium est porro tempora.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 798, DateTimeKind.Local).AddTicks(6473),
                            IsDeleted = false,
                            PreviewId = 23,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 798, DateTimeKind.Local).AddTicks(6507)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 14,
                            Body = "Qui vitae et qui rerum.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 798, DateTimeKind.Local).AddTicks(6757),
                            IsDeleted = false,
                            PreviewId = 33,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 798, DateTimeKind.Local).AddTicks(6782)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 17,
                            Body = "Mollitia ut inventore quam quam ut. Occaecati excepturi impedit ea libero labore voluptatem. Nostrum tenetur voluptas molestias animi alias ad. Minima quisquam delectus et itaque ut deleniti quasi temporibus enim. Sequi sit sit ipsa enim consequatur quidem laborum.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 798, DateTimeKind.Local).AddTicks(9780),
                            IsDeleted = false,
                            PreviewId = 26,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 798, DateTimeKind.Local).AddTicks(9827)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 4,
                            Body = "Unde quis aliquid optio necessitatibus totam odit ducimus voluptatem. Omnis cumque qui molestiae et veniam. Quidem sunt ex.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 799, DateTimeKind.Local).AddTicks(284),
                            IsDeleted = false,
                            PreviewId = 32,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 799, DateTimeKind.Local).AddTicks(319)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 6,
                            Body = "Dolores eos sapiente iure repellat aspernatur ea distinctio consequuntur quis.\nRerum repellendus sit voluptatem quia eius quo et.\nLaboriosam illum earum maiores.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 799, DateTimeKind.Local).AddTicks(595),
                            IsDeleted = false,
                            PreviewId = 27,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 799, DateTimeKind.Local).AddTicks(607)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 6,
                            Body = "ut",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 799, DateTimeKind.Local).AddTicks(1618),
                            IsDeleted = false,
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 799, DateTimeKind.Local).AddTicks(1649)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 7,
                            Body = "Vitae repellendus qui voluptas qui inventore voluptatem quis esse.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 799, DateTimeKind.Local).AddTicks(1891),
                            IsDeleted = false,
                            PreviewId = 21,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 799, DateTimeKind.Local).AddTicks(1903)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 6,
                            Body = "alias",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 799, DateTimeKind.Local).AddTicks(1974),
                            IsDeleted = false,
                            PreviewId = 28,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 799, DateTimeKind.Local).AddTicks(1984)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 15,
                            Body = "Ratione ex voluptas rerum accusantium.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 799, DateTimeKind.Local).AddTicks(2087),
                            IsDeleted = false,
                            PreviewId = 32,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 799, DateTimeKind.Local).AddTicks(2099)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 16,
                            Body = "reiciendis",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 799, DateTimeKind.Local).AddTicks(2167),
                            IsDeleted = false,
                            PreviewId = 22,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 799, DateTimeKind.Local).AddTicks(2177)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 4,
                            Body = "Vero doloribus officiis et alias temporibus doloribus et nesciunt sint. Eum corporis dolores rerum voluptatibus. Repellat est sunt natus repudiandae inventore necessitatibus illo numquam porro.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 799, DateTimeKind.Local).AddTicks(2541),
                            IsDeleted = false,
                            PreviewId = 23,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 799, DateTimeKind.Local).AddTicks(2558)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 9,
                            Body = "error",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 799, DateTimeKind.Local).AddTicks(2651),
                            IsDeleted = false,
                            PreviewId = 27,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 799, DateTimeKind.Local).AddTicks(2661)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 3,
                            Body = "totam",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 799, DateTimeKind.Local).AddTicks(2725),
                            IsDeleted = false,
                            PreviewId = 22,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 799, DateTimeKind.Local).AddTicks(2734)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 19,
                            Body = "Voluptatem vitae adipisci consequatur perspiciatis velit ut sit.\nRepellat consequuntur possimus enim et.\nEarum non voluptatibus placeat temporibus quasi.",
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 799, DateTimeKind.Local).AddTicks(3019),
                            IsDeleted = false,
                            PreviewId = 38,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 799, DateTimeKind.Local).AddTicks(3034)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDislike")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("PostId", "UserId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("UserId");

                    b.ToTable("PostReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 851, DateTimeKind.Local).AddTicks(8901),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = true,
                            PostId = 1,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(26),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1043),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = false,
                            PostId = 8,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1059),
                            UserId = 16
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1123),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = true,
                            PostId = 4,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1131),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1181),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = false,
                            PostId = 7,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1188),
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1238),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = false,
                            PostId = 17,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1245),
                            UserId = 13
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1295),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = true,
                            PostId = 16,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1303),
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1350),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = true,
                            PostId = 14,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1357),
                            UserId = 4
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1403),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = false,
                            PostId = 6,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1411),
                            UserId = 6
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1456),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = false,
                            PostId = 17,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1463),
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1511),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = false,
                            PostId = 20,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1518),
                            UserId = 20
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1562),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = false,
                            PostId = 4,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1570),
                            UserId = 6
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1616),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = false,
                            PostId = 13,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1625),
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1669),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = true,
                            PostId = 13,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1676),
                            UserId = 9
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1721),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = false,
                            PostId = 10,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1729),
                            UserId = 2
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1801),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = false,
                            PostId = 19,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1809),
                            UserId = 16
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1857),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = true,
                            PostId = 1,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1864),
                            UserId = 7
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1909),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = true,
                            PostId = 4,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1918),
                            UserId = 8
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1964),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = false,
                            PostId = 20,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(1972),
                            UserId = 14
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(2016),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = false,
                            PostId = 17,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(2023),
                            UserId = 14
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(2068),
                            IsDeleted = false,
                            IsDislike = false,
                            IsLike = false,
                            PostId = 7,
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 852, DateTimeKind.Local).AddTicks(2077),
                            UserId = 21
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AvatarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 6,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 442, DateTimeKind.Local).AddTicks(1971),
                            Email = "Sunny70@hotmail.com",
                            Password = "+HezI89i00p1jfZYAcqicc2hbsn8gWpdjXeQiA7O4tg=",
                            Salt = "14Wx6TCxqRBk9455JEGtVwXpkUMIH86vEjgwYlBqX3g=",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 442, DateTimeKind.Local).AddTicks(3282),
                            UserName = "Ericka.Goyette"
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 5,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 461, DateTimeKind.Local).AddTicks(1336),
                            Email = "Zoie_Connelly85@gmail.com",
                            Password = "wlPlYY9puRh2GjB/cADlr5dOTYmXHHj8rzFjB+aFWJ8=",
                            Salt = "aIzZBl0b+wt6OIKKJqV6e3CK8bKNxtfAQNPgy8aBV04=",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 461, DateTimeKind.Local).AddTicks(1480),
                            UserName = "Selmer65"
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 11,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 474, DateTimeKind.Local).AddTicks(138),
                            Email = "Hermann_Cartwright@gmail.com",
                            Password = "MRXZJKyt1TGC7SxmvIJIVMZ+r2aHhY/tD9EostnafSQ=",
                            Salt = "9Ca69VL0Zy9Kj7+pv63xL6xdsF7jTrSvRSTDKvtAQ3o=",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 474, DateTimeKind.Local).AddTicks(270),
                            UserName = "Alfred.Nader"
                        },
                        new
                        {
                            Id = 4,
                            AvatarId = 2,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 486, DateTimeKind.Local).AddTicks(6505),
                            Email = "Isadore_Douglas@hotmail.com",
                            Password = "SJ3BPE/8SvS74QABXfsn4pU9Hb5ozOuS4VQuRGkeM9o=",
                            Salt = "zM/XGfXcBAxQPjWLi+4TBHqsII/uaE9ndXQc89UY58Q=",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 486, DateTimeKind.Local).AddTicks(6647),
                            UserName = "Yvette_Adams"
                        },
                        new
                        {
                            Id = 5,
                            AvatarId = 5,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 501, DateTimeKind.Local).AddTicks(1149),
                            Email = "Mallory_Mitchell@yahoo.com",
                            Password = "TwLsTYc8Fdrcj9g9HdzsDtIizPqVjCg7SYX26C94WP0=",
                            Salt = "9Ph7J0UP8gQJMfJ94JJe0sD+3ElpTqG+gRCzW2XjyAY=",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 501, DateTimeKind.Local).AddTicks(1288),
                            UserName = "John_Wisoky"
                        },
                        new
                        {
                            Id = 6,
                            AvatarId = 7,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 516, DateTimeKind.Local).AddTicks(2100),
                            Email = "Oliver38@hotmail.com",
                            Password = "oq4I4TLCDIU8G6AFpgA38crvj+fkduFz/6an9DTB2/Q=",
                            Salt = "HsIeL1P5tzbwWnZrcgK+Hyw5uzncMz8VFyOrdX4JdFE=",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 516, DateTimeKind.Local).AddTicks(2229),
                            UserName = "Erna_Kuhn74"
                        },
                        new
                        {
                            Id = 7,
                            AvatarId = 5,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 528, DateTimeKind.Local).AddTicks(3588),
                            Email = "Gunnar_Abernathy@yahoo.com",
                            Password = "9wsSy+ecn6uukACZyeaKuJ2chREzgRdCJIqtBg77IjI=",
                            Salt = "glHOB9tN5VeVJrhasOKa1E9SWQuhtZu/fw4O+aLrSUg=",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 528, DateTimeKind.Local).AddTicks(3755),
                            UserName = "Betty54"
                        },
                        new
                        {
                            Id = 8,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 542, DateTimeKind.Local).AddTicks(5754),
                            Email = "Samanta_Padberg27@gmail.com",
                            Password = "fgUdr4+BmplVEAc1UXagi/dPwZjeR7YJdMQHOuolryU=",
                            Salt = "W7y6GkBC5pLs8WIoBM7oaztHiIlJiJLmtqV/KurIe50=",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 542, DateTimeKind.Local).AddTicks(5902),
                            UserName = "Jadyn10"
                        },
                        new
                        {
                            Id = 9,
                            AvatarId = 4,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 556, DateTimeKind.Local).AddTicks(5394),
                            Email = "Kelley_Koepp@hotmail.com",
                            Password = "Yq68QJobKL6+Y86eeoBoPX5NazAuKrn+MYnDL88aTJs=",
                            Salt = "+dK/KcNLJpGKUynKu3pC+3ImvPlE6loKagKgg985Hnk=",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 556, DateTimeKind.Local).AddTicks(5525),
                            UserName = "Ubaldo.Hegmann76"
                        },
                        new
                        {
                            Id = 10,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 573, DateTimeKind.Local).AddTicks(348),
                            Email = "Amira55@yahoo.com",
                            Password = "P2lOENxVM6VnnzJRm7jIxydvqqmHRU9ntHsKSkOD3Og=",
                            Salt = "Y6M+k/rAZf1EFi8kW6QM7d6LcktTnlKcXvgao9k/tok=",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 573, DateTimeKind.Local).AddTicks(497),
                            UserName = "Zita_Dibbert0"
                        },
                        new
                        {
                            Id = 11,
                            AvatarId = 1,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 586, DateTimeKind.Local).AddTicks(8290),
                            Email = "Carolanne59@gmail.com",
                            Password = "kyLpUjwPC9Ij8DcZk4PQf2VOK2ocsqj886qLPCyIPwo=",
                            Salt = "JAqr8KVDOlx4Omu1NUZxJKvKcgzOySk0f9LD40haUBE=",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 586, DateTimeKind.Local).AddTicks(8522),
                            UserName = "Tianna.Kuhlman"
                        },
                        new
                        {
                            Id = 12,
                            AvatarId = 17,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 598, DateTimeKind.Local).AddTicks(8421),
                            Email = "Sigurd.Lang@hotmail.com",
                            Password = "vm158B66IEjzE5EhtAKLlAtaW5fxXLvxQSkFg6vIjt4=",
                            Salt = "JM3TfJ40kqr7Ta3v8GymVpna92rpdw4IubH6JG1FXts=",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 598, DateTimeKind.Local).AddTicks(8558),
                            UserName = "Jaime_Osinski"
                        },
                        new
                        {
                            Id = 13,
                            AvatarId = 9,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 618, DateTimeKind.Local).AddTicks(476),
                            Email = "Maximillian_Wilkinson46@gmail.com",
                            Password = "VIzB/+h2P8F3ANGGFyHfE06qEPhIpzOyII3RMWKOpF8=",
                            Salt = "YQDD1H0erMEtbHyZ2QzhHJYVrjiMAvcG8xD+NnLvTIs=",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 618, DateTimeKind.Local).AddTicks(619),
                            UserName = "Adella.Zboncak"
                        },
                        new
                        {
                            Id = 14,
                            AvatarId = 13,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 638, DateTimeKind.Local).AddTicks(739),
                            Email = "Elwin14@yahoo.com",
                            Password = "5F82wRvE0kYAMAfteu+WAhPyX7PAQUA1ZCyiJdAdZFc=",
                            Salt = "UQi48bY8ozmrUIpXGhFOn0ZNDU3xrXuop4+Cp/gp8IE=",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 638, DateTimeKind.Local).AddTicks(891),
                            UserName = "Reba92"
                        },
                        new
                        {
                            Id = 15,
                            AvatarId = 10,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 658, DateTimeKind.Local).AddTicks(634),
                            Email = "Elisha13@gmail.com",
                            Password = "9oVPRpa73YI39IOdaNoj0HMu9RWswYgjrC88UmZOqQc=",
                            Salt = "2vA8sF8hddmdrh1mO36+oGN0EK0It+Q5Tmn7KYB9I+k=",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 658, DateTimeKind.Local).AddTicks(815),
                            UserName = "Keagan.Swaniawski"
                        },
                        new
                        {
                            Id = 16,
                            AvatarId = 16,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 677, DateTimeKind.Local).AddTicks(209),
                            Email = "Armando_Torp85@hotmail.com",
                            Password = "2i7/v2Fj/OrqI4FWlor6cUVchykInYTOVfoP7nq5gBI=",
                            Salt = "Tk5mkBfBjcBqOHwR2syJLduNtc6mRneovTW1CmTQGcc=",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 677, DateTimeKind.Local).AddTicks(411),
                            UserName = "Herbert51"
                        },
                        new
                        {
                            Id = 17,
                            AvatarId = 17,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 697, DateTimeKind.Local).AddTicks(811),
                            Email = "Joe_Bartell@yahoo.com",
                            Password = "L5NxMUNOOpUJnybzPbFsuZ22hT7XlQPgUbrm9zqH+4U=",
                            Salt = "UlhLGiiopkFvp0sMTt9r0y3NhXReIihF6KuIZhkup7s=",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 697, DateTimeKind.Local).AddTicks(989),
                            UserName = "Mia89"
                        },
                        new
                        {
                            Id = 18,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 716, DateTimeKind.Local).AddTicks(9990),
                            Email = "Marcus.Jakubowski74@hotmail.com",
                            Password = "PNqQFw3G5YjJ6zDUwROk5db9MEsTfKIjofc8AL/3nfw=",
                            Salt = "PBlQcWkNRZVbqd2kZX/SBUk9kY6Wgw3mE/VhXwI6zIQ=",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 717, DateTimeKind.Local).AddTicks(159),
                            UserName = "Orval32"
                        },
                        new
                        {
                            Id = 19,
                            AvatarId = 7,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 737, DateTimeKind.Local).AddTicks(9616),
                            Email = "Damian_Beier56@gmail.com",
                            Password = "aTeTOVBx3LAQgNQPzlPWESQbbCgQbOevkY0MLdB2XjI=",
                            Salt = "+xIWBO/1I+BrubVGoX3GGds0bfJyKskcaGLrWNfP49A=",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 737, DateTimeKind.Local).AddTicks(9861),
                            UserName = "Randal2"
                        },
                        new
                        {
                            Id = 20,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 760, DateTimeKind.Local).AddTicks(7705),
                            Email = "Ashlee85@gmail.com",
                            Password = "80f1atewhQ0aVfdUVaiJaSpm9X4UOb/vKlLfrTXWWqU=",
                            Salt = "9J9QICcQwMBmVGA0wPmQFhgRNfMlgWkbVbYHWKO8IDI=",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 760, DateTimeKind.Local).AddTicks(7902),
                            UserName = "Annabel25"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 774, DateTimeKind.Local).AddTicks(5900),
                            Email = "test@gmail.com",
                            Password = "mAjoIwmDI0k6VZYhNtisMyD7pxsInhxdEWsVxcWfPyA=",
                            Salt = "EMEdLVHZL8YbhczTnaWk+SBVKJk6ngOruUk6J5lFTII=",
                            UpdatedAt = new DateTime(2021, 6, 12, 16, 16, 25, 774, DateTimeKind.Local).AddTicks(5900),
                            UserName = "testUser"
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Preview")
                        .WithMany()
                        .HasForeignKey("PreviewId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");

                    b.Navigation("Preview");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });
#pragma warning restore 612, 618
        }
    }
}
