// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thread_.NET.DAL.Context;

namespace Thread_.NET.DAL.Migrations
{
    [DbContext(typeof(ThreadContext))]
    partial class ThreadContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 15,
                            Body = "Assumenda laborum dolorem eum pariatur repellat quia.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(1337),
                            PostId = 7,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(2524)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 15,
                            Body = "Quae dolorem expedita dolores consequatur qui eum incidunt.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(3647),
                            PostId = 10,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(3666)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 17,
                            Body = "Modi vel alias.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(3774),
                            PostId = 3,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(3784)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 7,
                            Body = "Eum amet porro voluptates est ut consectetur.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(3903),
                            PostId = 5,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(3913)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 21,
                            Body = "Similique iure voluptates esse temporibus beatae maiores.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(4024),
                            PostId = 10,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(4034)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 8,
                            Body = "Iure enim voluptatum eum.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(4256),
                            PostId = 12,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(4267)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 4,
                            Body = "Iste unde ut.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(4460),
                            PostId = 12,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(4475)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 4,
                            Body = "Voluptate autem excepturi et autem quia ut laudantium.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(4600),
                            PostId = 12,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(4610)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 5,
                            Body = "Voluptatem voluptas omnis illo minima ratione reprehenderit ipsa voluptas saepe.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(4742),
                            PostId = 11,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(4752)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 21,
                            Body = "Necessitatibus similique ratione debitis harum repellendus perferendis in.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(4864),
                            PostId = 14,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(4875)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 5,
                            Body = "Ipsa ad qui adipisci rerum numquam facere.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(4975),
                            PostId = 15,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(4985)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 3,
                            Body = "Error et qui ut minima in voluptas.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(5152),
                            PostId = 6,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(5166)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 12,
                            Body = "Sed vero et id modi quia reprehenderit fugiat vel.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(5293),
                            PostId = 10,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(5304)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 5,
                            Body = "Consectetur quaerat perferendis alias optio.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(5396),
                            PostId = 9,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(5407)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 3,
                            Body = "Qui voluptatibus est.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(5487),
                            PostId = 7,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(5497)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 9,
                            Body = "Voluptas et ex.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(5581),
                            PostId = 4,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(5591)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 15,
                            Body = "Id vel ullam amet voluptatum.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(5681),
                            PostId = 20,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(5691)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 7,
                            Body = "Dolorem et nulla adipisci aut quis.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(5788),
                            PostId = 12,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(5797)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 4,
                            Body = "Minima nihil rerum est qui cumque eius vitae soluta velit.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(5976),
                            PostId = 18,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(5991)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 21,
                            Body = "Deleniti asperiores vel quia ut vel.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(6095),
                            PostId = 17,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 501, DateTimeKind.Local).AddTicks(6106)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDislike")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("CommentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentId = 16,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 541, DateTimeKind.Local).AddTicks(7285),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 541, DateTimeKind.Local).AddTicks(8498),
                            UserId = 6
                        },
                        new
                        {
                            Id = 2,
                            CommentId = 17,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 541, DateTimeKind.Local).AddTicks(9489),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 541, DateTimeKind.Local).AddTicks(9514),
                            UserId = 7
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 7,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 541, DateTimeKind.Local).AddTicks(9625),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 541, DateTimeKind.Local).AddTicks(9641),
                            UserId = 18
                        },
                        new
                        {
                            Id = 4,
                            CommentId = 16,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 541, DateTimeKind.Local).AddTicks(9732),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 541, DateTimeKind.Local).AddTicks(9747),
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            CommentId = 20,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 541, DateTimeKind.Local).AddTicks(9840),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 541, DateTimeKind.Local).AddTicks(9854),
                            UserId = 14
                        },
                        new
                        {
                            Id = 6,
                            CommentId = 19,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 541, DateTimeKind.Local).AddTicks(9941),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 541, DateTimeKind.Local).AddTicks(9956),
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            CommentId = 17,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 542, DateTimeKind.Local).AddTicks(76),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 542, DateTimeKind.Local).AddTicks(93),
                            UserId = 12
                        },
                        new
                        {
                            Id = 8,
                            CommentId = 20,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 542, DateTimeKind.Local).AddTicks(183),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 542, DateTimeKind.Local).AddTicks(198),
                            UserId = 12
                        },
                        new
                        {
                            Id = 9,
                            CommentId = 14,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 542, DateTimeKind.Local).AddTicks(289),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 542, DateTimeKind.Local).AddTicks(303),
                            UserId = 17
                        },
                        new
                        {
                            Id = 10,
                            CommentId = 1,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 542, DateTimeKind.Local).AddTicks(435),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 542, DateTimeKind.Local).AddTicks(454),
                            UserId = 9
                        },
                        new
                        {
                            Id = 11,
                            CommentId = 10,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 542, DateTimeKind.Local).AddTicks(547),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 542, DateTimeKind.Local).AddTicks(563),
                            UserId = 21
                        },
                        new
                        {
                            Id = 12,
                            CommentId = 17,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 542, DateTimeKind.Local).AddTicks(657),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 542, DateTimeKind.Local).AddTicks(672),
                            UserId = 15
                        },
                        new
                        {
                            Id = 13,
                            CommentId = 2,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 542, DateTimeKind.Local).AddTicks(758),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 542, DateTimeKind.Local).AddTicks(773),
                            UserId = 12
                        },
                        new
                        {
                            Id = 14,
                            CommentId = 15,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 542, DateTimeKind.Local).AddTicks(863),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 542, DateTimeKind.Local).AddTicks(877),
                            UserId = 20
                        },
                        new
                        {
                            Id = 15,
                            CommentId = 15,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 542, DateTimeKind.Local).AddTicks(965),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 542, DateTimeKind.Local).AddTicks(981),
                            UserId = 8
                        },
                        new
                        {
                            Id = 16,
                            CommentId = 13,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 542, DateTimeKind.Local).AddTicks(1071),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 542, DateTimeKind.Local).AddTicks(1086),
                            UserId = 5
                        },
                        new
                        {
                            Id = 17,
                            CommentId = 13,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 542, DateTimeKind.Local).AddTicks(1173),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 542, DateTimeKind.Local).AddTicks(1187),
                            UserId = 3
                        },
                        new
                        {
                            Id = 18,
                            CommentId = 16,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 542, DateTimeKind.Local).AddTicks(1274),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 542, DateTimeKind.Local).AddTicks(1289),
                            UserId = 21
                        },
                        new
                        {
                            Id = 19,
                            CommentId = 15,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 542, DateTimeKind.Local).AddTicks(1378),
                            IsDislike = false,
                            IsLike = true,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 542, DateTimeKind.Local).AddTicks(1392),
                            UserId = 16
                        },
                        new
                        {
                            Id = 20,
                            CommentId = 10,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 542, DateTimeKind.Local).AddTicks(1479),
                            IsDislike = false,
                            IsLike = false,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 542, DateTimeKind.Local).AddTicks(1492),
                            UserId = 19
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 68, DateTimeKind.Local).AddTicks(1709),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/684.jpg",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 68, DateTimeKind.Local).AddTicks(8403)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 68, DateTimeKind.Local).AddTicks(9425),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/929.jpg",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 68, DateTimeKind.Local).AddTicks(9439)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 68, DateTimeKind.Local).AddTicks(9615),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1189.jpg",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 68, DateTimeKind.Local).AddTicks(9626)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 68, DateTimeKind.Local).AddTicks(9667),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1120.jpg",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 68, DateTimeKind.Local).AddTicks(9674)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 68, DateTimeKind.Local).AddTicks(9706),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1015.jpg",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 68, DateTimeKind.Local).AddTicks(9713)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 68, DateTimeKind.Local).AddTicks(9745),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/644.jpg",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 68, DateTimeKind.Local).AddTicks(9753)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 68, DateTimeKind.Local).AddTicks(9783),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/487.jpg",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 68, DateTimeKind.Local).AddTicks(9791)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 68, DateTimeKind.Local).AddTicks(9823),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/112.jpg",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 68, DateTimeKind.Local).AddTicks(9831)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 68, DateTimeKind.Local).AddTicks(9861),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1005.jpg",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 68, DateTimeKind.Local).AddTicks(9869)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 68, DateTimeKind.Local).AddTicks(9900),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/362.jpg",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 68, DateTimeKind.Local).AddTicks(9908)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 68, DateTimeKind.Local).AddTicks(9941),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/81.jpg",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 68, DateTimeKind.Local).AddTicks(9948)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 68, DateTimeKind.Local).AddTicks(9979),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/994.jpg",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 68, DateTimeKind.Local).AddTicks(9987)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 69, DateTimeKind.Local).AddTicks(19),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/514.jpg",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 69, DateTimeKind.Local).AddTicks(27)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 69, DateTimeKind.Local).AddTicks(63),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/485.jpg",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 69, DateTimeKind.Local).AddTicks(71)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 69, DateTimeKind.Local).AddTicks(104),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/895.jpg",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 69, DateTimeKind.Local).AddTicks(112)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 69, DateTimeKind.Local).AddTicks(145),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/19.jpg",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 69, DateTimeKind.Local).AddTicks(153)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 69, DateTimeKind.Local).AddTicks(186),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/150.jpg",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 69, DateTimeKind.Local).AddTicks(194)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 69, DateTimeKind.Local).AddTicks(227),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/171.jpg",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 69, DateTimeKind.Local).AddTicks(235)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 69, DateTimeKind.Local).AddTicks(268),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/123.jpg",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 69, DateTimeKind.Local).AddTicks(276)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 69, DateTimeKind.Local).AddTicks(309),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/482.jpg",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 69, DateTimeKind.Local).AddTicks(317)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(6284),
                            URL = "https://picsum.photos/640/480/?image=198",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(7517)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(7951),
                            URL = "https://picsum.photos/640/480/?image=743",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(7962)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8000),
                            URL = "https://picsum.photos/640/480/?image=538",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8009)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8042),
                            URL = "https://picsum.photos/640/480/?image=542",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8051)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8083),
                            URL = "https://picsum.photos/640/480/?image=413",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8092)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8126),
                            URL = "https://picsum.photos/640/480/?image=394",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8135)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8170),
                            URL = "https://picsum.photos/640/480/?image=405",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8179)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8211),
                            URL = "https://picsum.photos/640/480/?image=788",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8220)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8252),
                            URL = "https://picsum.photos/640/480/?image=828",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8261)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8294),
                            URL = "https://picsum.photos/640/480/?image=745",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8302)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8334),
                            URL = "https://picsum.photos/640/480/?image=1069",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8343)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8374),
                            URL = "https://picsum.photos/640/480/?image=231",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8382)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8502),
                            URL = "https://picsum.photos/640/480/?image=2",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8515)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8555),
                            URL = "https://picsum.photos/640/480/?image=302",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8564)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8600),
                            URL = "https://picsum.photos/640/480/?image=29",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8609)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8643),
                            URL = "https://picsum.photos/640/480/?image=77",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8652)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8683),
                            URL = "https://picsum.photos/640/480/?image=893",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8693)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8725),
                            URL = "https://picsum.photos/640/480/?image=345",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8733)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8766),
                            URL = "https://picsum.photos/640/480/?image=883",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8774)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8806),
                            URL = "https://picsum.photos/640/480/?image=1008",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 79, DateTimeKind.Local).AddTicks(8814)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("PreviewId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PreviewId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 20,
                            Body = "Necessitatibus reiciendis debitis. Ipsa iusto quis. Quo id blanditiis saepe fuga molestiae.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 485, DateTimeKind.Local).AddTicks(8598),
                            IsDeleted = false,
                            PreviewId = 26,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 486, DateTimeKind.Local).AddTicks(379)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 8,
                            Body = "soluta",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 486, DateTimeKind.Local).AddTicks(2717),
                            IsDeleted = false,
                            PreviewId = 28,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 486, DateTimeKind.Local).AddTicks(2759)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Body = "explicabo",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 486, DateTimeKind.Local).AddTicks(3004),
                            IsDeleted = false,
                            PreviewId = 36,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 486, DateTimeKind.Local).AddTicks(3031)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 17,
                            Body = "Suscipit dolorem nemo non maiores et autem consectetur autem ut. Omnis sit reiciendis corrupti. Amet suscipit quo assumenda quia non sequi facere qui qui. Vero quibusdam velit et sed qui et hic dolore. Non rem et dolore id blanditiis.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 486, DateTimeKind.Local).AddTicks(4936),
                            IsDeleted = false,
                            PreviewId = 33,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 486, DateTimeKind.Local).AddTicks(4974)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 10,
                            Body = "Tempore ipsum deserunt cum incidunt dolorem. Quia perferendis iste possimus sed autem occaecati reprehenderit. In beatae voluptas occaecati accusantium labore sint. Eos totam occaecati rem possimus molestias rerum unde.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 486, DateTimeKind.Local).AddTicks(5690),
                            IsDeleted = false,
                            PreviewId = 22,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 486, DateTimeKind.Local).AddTicks(5733)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 4,
                            Body = "fuga",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 486, DateTimeKind.Local).AddTicks(5968),
                            IsDeleted = false,
                            PreviewId = 33,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 486, DateTimeKind.Local).AddTicks(5987)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 5,
                            Body = "Dolorem incidunt pariatur est itaque ducimus qui nisi eos. Qui in vero consequatur. Expedita recusandae vel omnis corporis quaerat. Molestias laborum quia praesentium sit. Assumenda maiores non consectetur cumque.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 486, DateTimeKind.Local).AddTicks(6699),
                            IsDeleted = false,
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 486, DateTimeKind.Local).AddTicks(6728)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 20,
                            Body = "libero",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 486, DateTimeKind.Local).AddTicks(6886),
                            IsDeleted = false,
                            PreviewId = 38,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 486, DateTimeKind.Local).AddTicks(6907)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 19,
                            Body = "autem",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 486, DateTimeKind.Local).AddTicks(7034),
                            IsDeleted = false,
                            PreviewId = 23,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 486, DateTimeKind.Local).AddTicks(7052)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 15,
                            Body = "Aut eius explicabo placeat.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 486, DateTimeKind.Local).AddTicks(8920),
                            IsDeleted = false,
                            PreviewId = 40,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 486, DateTimeKind.Local).AddTicks(8976)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 5,
                            Body = "Quia sint praesentium.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 486, DateTimeKind.Local).AddTicks(9199),
                            IsDeleted = false,
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 486, DateTimeKind.Local).AddTicks(9222)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 17,
                            Body = "Reprehenderit sunt officiis.\nUt officiis aut.\nMolestiae maiores quae necessitatibus.\nExcepturi magni rem dolore in ut et ut.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 487, DateTimeKind.Local).AddTicks(1117),
                            IsDeleted = false,
                            PreviewId = 32,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 487, DateTimeKind.Local).AddTicks(1161)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 12,
                            Body = "Et vel tempora quod veniam et voluptatem ducimus ut.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 487, DateTimeKind.Local).AddTicks(1565),
                            IsDeleted = false,
                            PreviewId = 28,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 487, DateTimeKind.Local).AddTicks(1594)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 3,
                            Body = "tempora",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 487, DateTimeKind.Local).AddTicks(1751),
                            IsDeleted = false,
                            PreviewId = 34,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 487, DateTimeKind.Local).AddTicks(1768)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 21,
                            Body = "non",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 487, DateTimeKind.Local).AddTicks(1892),
                            IsDeleted = false,
                            PreviewId = 27,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 487, DateTimeKind.Local).AddTicks(1909)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 13,
                            Body = "Vel iure doloribus voluptatum quo sit.\nAut consequatur est natus.\nRem dolores aut nihil.\nOmnis qui dignissimos voluptas.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 487, DateTimeKind.Local).AddTicks(3133),
                            IsDeleted = false,
                            PreviewId = 23,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 487, DateTimeKind.Local).AddTicks(3180)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 6,
                            Body = "Quisquam dolores eos.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 487, DateTimeKind.Local).AddTicks(3472),
                            IsDeleted = false,
                            PreviewId = 27,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 487, DateTimeKind.Local).AddTicks(3501)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 18,
                            Body = "Nobis similique voluptas facere aut. Maiores non voluptatem officia dolor laudantium doloremque. Id modi molestias dolor. Ut quae ut cumque vel perspiciatis. Fugit velit aspernatur in unde a.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 487, DateTimeKind.Local).AddTicks(4222),
                            IsDeleted = false,
                            PreviewId = 38,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 487, DateTimeKind.Local).AddTicks(4249)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 4,
                            Body = "Libero laboriosam a. Incidunt qui occaecati autem voluptatibus doloribus occaecati provident. Autem vitae eum dolor corporis qui et doloremque non ut. Temporibus fugit dignissimos ipsa qui officia. Esse tempore dolor voluptas. Voluptatum nesciunt illum quisquam dolor sit natus rem mollitia.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 487, DateTimeKind.Local).AddTicks(7804),
                            IsDeleted = false,
                            PreviewId = 34,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 487, DateTimeKind.Local).AddTicks(7842)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 11,
                            Body = "Explicabo omnis facilis veritatis perferendis blanditiis doloribus. Tenetur sed autem deleniti ut qui. Aut vero minus tenetur labore voluptates fuga atque quam. Aut est debitis aut quia non distinctio sunt.",
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 487, DateTimeKind.Local).AddTicks(8314),
                            IsDeleted = false,
                            PreviewId = 25,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 487, DateTimeKind.Local).AddTicks(8330)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDislike")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("PostId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PostReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(3205),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 5,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(4545),
                            UserId = 21
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(6022),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 5,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(6053),
                            UserId = 7
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(6246),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 1,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(6264),
                            UserId = 13
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(6355),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 16,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(6369),
                            UserId = 16
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(6457),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 14,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(6471),
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(6556),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 12,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(6571),
                            UserId = 12
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(6659),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 3,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(6676),
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(6758),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 17,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(6772),
                            UserId = 7
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(6851),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 9,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(6864),
                            UserId = 8
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(6945),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 19,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(6959),
                            UserId = 18
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(7037),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 13,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(7052),
                            UserId = 20
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(7128),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 15,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(7142),
                            UserId = 16
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(7223),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 18,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(7237),
                            UserId = 17
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(7314),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 11,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(7328),
                            UserId = 2
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(7408),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 8,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(7421),
                            UserId = 8
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(7497),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 9,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(7511),
                            UserId = 12
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(7589),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 14,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(7603),
                            UserId = 18
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(7676),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 18,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(7688),
                            UserId = 6
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(7765),
                            IsDislike = false,
                            IsLike = false,
                            PostId = 14,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(7779),
                            UserId = 16
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(7850),
                            IsDislike = false,
                            IsLike = true,
                            PostId = 19,
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 514, DateTimeKind.Local).AddTicks(7864),
                            UserId = 7
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AvatarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 13,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 157, DateTimeKind.Local).AddTicks(6064),
                            Email = "Myra_Wilkinson38@gmail.com",
                            Password = "S5AE3lv1qBSHNqH68peolLqSkWgt/FnhCkZaVABW8pc=",
                            Salt = "aIVA6vcRE6wcGYKH0BBD/rsHF6BwUISNEoyFsbk40fE=",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 157, DateTimeKind.Local).AddTicks(7195),
                            UserName = "Arely.Schmeler15"
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 15,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 170, DateTimeKind.Local).AddTicks(5679),
                            Email = "Gerhard34@gmail.com",
                            Password = "ht4qejvoIf/5CW8SR97aSSgEBkFV0/BXrKcflyiESzA=",
                            Salt = "5Qlf2VqUavYfobjGtpS/ybeMmjIvTlyUE7/MMFjkJTw=",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 170, DateTimeKind.Local).AddTicks(5808),
                            UserName = "Claudine16"
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 183, DateTimeKind.Local).AddTicks(4402),
                            Email = "Armando.Hermann@yahoo.com",
                            Password = "aVyzlxC3p1lmAQrZ8Zbx819UbvMUEAQvSbL8d3PLkN4=",
                            Salt = "5TZuCdiqSAU9CbFTZ9yBc5cBEOHRTfeycbw2WM/qbBU=",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 183, DateTimeKind.Local).AddTicks(4553),
                            UserName = "Assunta60"
                        },
                        new
                        {
                            Id = 4,
                            AvatarId = 12,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 197, DateTimeKind.Local).AddTicks(1493),
                            Email = "Thea_Streich93@hotmail.com",
                            Password = "edW0BE4dnwwGBH2bV6oa2V65ItD+MWIEh4tHNHrNv+k=",
                            Salt = "hF7K/dNS7HJ+DqUkj8+w1HZIY5Kh7ZKgvzYkObn/5qQ=",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 197, DateTimeKind.Local).AddTicks(1644),
                            UserName = "Adolph2"
                        },
                        new
                        {
                            Id = 5,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 210, DateTimeKind.Local).AddTicks(4822),
                            Email = "Bret80@hotmail.com",
                            Password = "0abRPv5sjIu/TPfVRNq8X89lDO1ZeDsa9MlgSXZKoUk=",
                            Salt = "WivnnGD0ZiYriJAsNCFgN+6d87ceVPqUb5Vy6qXFV1g=",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 210, DateTimeKind.Local).AddTicks(4946),
                            UserName = "Jayson12"
                        },
                        new
                        {
                            Id = 6,
                            AvatarId = 2,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 223, DateTimeKind.Local).AddTicks(1051),
                            Email = "Eldora68@gmail.com",
                            Password = "LTX2Jst1K9gpK96+iTRgdDOtKagOQXMbuXByB5xgI3k=",
                            Salt = "8bYl3Y6jlv0at3UU+bpF7MHyw0GyGpOZ+OMw0owqRBE=",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 223, DateTimeKind.Local).AddTicks(1208),
                            UserName = "Maximilian.Kemmer"
                        },
                        new
                        {
                            Id = 7,
                            AvatarId = 8,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 237, DateTimeKind.Local).AddTicks(8051),
                            Email = "Jade46@gmail.com",
                            Password = "MCBdu7JHMUgBelf4hm+3d8iA5G5mNvCRTpWCxvvPTDA=",
                            Salt = "4y/CUaJpN19jh5sIL1pGJXg34/wCxgcuYAQpgfKyvT0=",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 237, DateTimeKind.Local).AddTicks(8188),
                            UserName = "Ford_Bednar"
                        },
                        new
                        {
                            Id = 8,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 252, DateTimeKind.Local).AddTicks(3186),
                            Email = "Hazel63@yahoo.com",
                            Password = "I3rLjlSyjcZZ/c/1bkpkQnrWF6+DOZh61OJAYAmf8cs=",
                            Salt = "U5Xz3HC1Hf6VKd8WaijNFa9EpGhvkGeMge2WmsX3ZnY=",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 252, DateTimeKind.Local).AddTicks(3318),
                            UserName = "Verna.Fahey10"
                        },
                        new
                        {
                            Id = 9,
                            AvatarId = 12,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 266, DateTimeKind.Local).AddTicks(2843),
                            Email = "Garnet.Leuschke@gmail.com",
                            Password = "VSLnGqSYoMzVw+JaEsGiaBqUaIaQxz9LwZ+mB7L8OUI=",
                            Salt = "T6t/ZoYTDIDt0yAwQQNURB9wajzFWY2v1mph/y13R90=",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 266, DateTimeKind.Local).AddTicks(2984),
                            UserName = "Emie_Schumm"
                        },
                        new
                        {
                            Id = 10,
                            AvatarId = 16,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 278, DateTimeKind.Local).AddTicks(1747),
                            Email = "Vince.Emard@gmail.com",
                            Password = "EFvsMqL+p7J9+GDJCllCj2IXOrsgemqKE9vXdbYFXJ4=",
                            Salt = "kiswa/2nOYl9juCx9TBpQb9HvCto9hCynldxZWsuh0c=",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 278, DateTimeKind.Local).AddTicks(1874),
                            UserName = "Albin_Reichel68"
                        },
                        new
                        {
                            Id = 11,
                            AvatarId = 10,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 291, DateTimeKind.Local).AddTicks(3327),
                            Email = "Johnny95@hotmail.com",
                            Password = "AW1QgAU4o08X9qHyTIjn8wk9X347pKXiIyLqRdCyekQ=",
                            Salt = "NZOt7BHdieryGeBa+Wy/oYZdamrSuikEiR5pYo7KlpQ=",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 291, DateTimeKind.Local).AddTicks(3453),
                            UserName = "Cleo47"
                        },
                        new
                        {
                            Id = 12,
                            AvatarId = 7,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 308, DateTimeKind.Local).AddTicks(4423),
                            Email = "Gunner90@yahoo.com",
                            Password = "GpCpPd4hLe3P3zmulEzT5UQzAYddZgt9I5DyeQ+NbAI=",
                            Salt = "ppFqBVwBR92hi4zPlcei9jDPWDoyUPCoySVXVSG0ReU=",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 308, DateTimeKind.Local).AddTicks(4567),
                            UserName = "Jarrett.Tremblay"
                        },
                        new
                        {
                            Id = 13,
                            AvatarId = 4,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 324, DateTimeKind.Local).AddTicks(6346),
                            Email = "Reuben.Cremin18@yahoo.com",
                            Password = "mKNwfwcXsczpaCZDw7VLeh5cViy+DqLPPQpf3ZkdZIs=",
                            Salt = "mzobJ3hHLcXa31nO14020jjZbV9KJJzfVjaSTwb9ZXQ=",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 324, DateTimeKind.Local).AddTicks(6468),
                            UserName = "Ashlynn_Kovacek8"
                        },
                        new
                        {
                            Id = 14,
                            AvatarId = 16,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 341, DateTimeKind.Local).AddTicks(6203),
                            Email = "Malvina_Prosacco@gmail.com",
                            Password = "JS1dAFOdT6DAiPiO/zHgowfga5sj22VHcnobQWvAAh8=",
                            Salt = "UnBiVsbEzWrQTiz2Yidnz9ErqugE+EvC4x5ARxd8cZw=",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 341, DateTimeKind.Local).AddTicks(6351),
                            UserName = "Timothy_Thiel"
                        },
                        new
                        {
                            Id = 15,
                            AvatarId = 13,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 356, DateTimeKind.Local).AddTicks(3663),
                            Email = "Benjamin_Purdy96@gmail.com",
                            Password = "WA4qQIbr/rh3W+ibpxPr4vYDayMWt6eKKT7spdPSNJw=",
                            Salt = "6CPqYdQJ7x+Jvur/rrV4OOd2p/njyN/Ye1M3nbCG6BI=",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 356, DateTimeKind.Local).AddTicks(3807),
                            UserName = "Zola_Hills"
                        },
                        new
                        {
                            Id = 16,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 373, DateTimeKind.Local).AddTicks(3332),
                            Email = "Noemie2@hotmail.com",
                            Password = "pFK5q5O1WwfQc+fPVyCBbLCGriwVrLDXoCBLS8b57C0=",
                            Salt = "itmyj1QagDanx91avTWImRBAwx3pTkEcO3Oherb0aiw=",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 373, DateTimeKind.Local).AddTicks(3489),
                            UserName = "Isaac37"
                        },
                        new
                        {
                            Id = 17,
                            AvatarId = 16,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 390, DateTimeKind.Local).AddTicks(4398),
                            Email = "Roma.Pollich55@yahoo.com",
                            Password = "qKE0RCf8T2/PckuB+Q/WA3twaw9WG2roLkv/w17U02s=",
                            Salt = "AAzVLPy+2pIlVt23uCUFWQ1X+LYxS5WnyLUkng1O6AY=",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 390, DateTimeKind.Local).AddTicks(4565),
                            UserName = "Rickey.Windler99"
                        },
                        new
                        {
                            Id = 18,
                            AvatarId = 1,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 405, DateTimeKind.Local).AddTicks(743),
                            Email = "Tony28@hotmail.com",
                            Password = "gs9Py7zbqnoUbNQQrkjKMVk0noiW9Lzpz4BdcYDrRJM=",
                            Salt = "bBwo2cB7h5bpdOiDFKXAiLLmCVBATkRnxlTGK1XViVc=",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 405, DateTimeKind.Local).AddTicks(902),
                            UserName = "Wilhelmine71"
                        },
                        new
                        {
                            Id = 19,
                            AvatarId = 12,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 416, DateTimeKind.Local).AddTicks(9685),
                            Email = "Blair_Adams@yahoo.com",
                            Password = "aWVbpt9SZa20o+zvNKm2cFzenExaO0RvzH2gvg9dZe4=",
                            Salt = "r5eqm0ezjeyK4KG4+R4XVGf9u7aXjATPYrRy5ie+9dg=",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 416, DateTimeKind.Local).AddTicks(9869),
                            UserName = "Arden.Homenick"
                        },
                        new
                        {
                            Id = 20,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 433, DateTimeKind.Local).AddTicks(9115),
                            Email = "Rhoda.Thiel@yahoo.com",
                            Password = "VeOF/6GvcwGi+Bzlc2SSl6GgkIXDeTdfM2PMGYUu5tE=",
                            Salt = "M8//Bo+SRASFfdK8chNQguDIdjm5e1dXcfXc9AlCTrY=",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 433, DateTimeKind.Local).AddTicks(9328),
                            UserName = "Winona.Bergnaum5"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 455, DateTimeKind.Local).AddTicks(3901),
                            Email = "test@gmail.com",
                            Password = "46kuwM2FmD0Ls7xkvKeluRq43mEqM0NpZRzsCnLEkVI=",
                            Salt = "FaxMNHVYAnEZinbGfN5Z+D5OJyh/i6mszAgs/ElUDys=",
                            UpdatedAt = new DateTime(2021, 6, 11, 23, 26, 37, 455, DateTimeKind.Local).AddTicks(3901),
                            UserName = "testUser"
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Preview")
                        .WithMany()
                        .HasForeignKey("PreviewId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");

                    b.Navigation("Preview");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });
#pragma warning restore 612, 618
        }
    }
}
